import type { PhotoSetId } from "./photoSets";

/**
 * Curated, geographically diverse places used by the World scenery set.
 * Ported verbatim from SurgeCode v0.2.7 WorldSceneryCatalog.swift.
 *
 * Keep names suitable for attribution labels and queries specific enough that
 * Unsplash returns the actual place rather than a generic photo of the country.
 */

export interface SceneryLocation {
  readonly name: string;
  readonly query: string;
}

export const WORLD_SCENERY_CATALOG: ReadonlyArray<SceneryLocation> = [
  /// Curated, geographically diverse places used by the built-in World scenery set.
  ///
  /// Keep names suitable for thread titles and queries specific enough that Unsplash
  /// returns the actual place rather than a generic photo from the surrounding country.
  // Europe
  { name: "Santorini, Greece", query: "santorini greece caldera" },
  { name: "Tre Cime, Italy", query: "tre cime dolomites italy" },
  { name: "Lofoten, Norway", query: "lofoten islands norway" },
  { name: "Zermatt, Switzerland", query: "matterhorn zermatt switzerland" },
  { name: "Sk\u00f3gafoss, Iceland", query: "skogafoss waterfall iceland" },
  { name: "Cappadocia, T\u00fcrkiye", query: "cappadocia turkey balloons" },
  { name: "Plitvice Lakes, Croatia", query: "plitvice lakes croatia" },
  { name: "Isle of Skye, United Kingdom", query: "isle of skye scotland" },
  { name: "Lake Bled, Slovenia", query: "lake bled slovenia" },
  { name: "Sete Cidades, Portugal", query: "sete cidades azores portugal" },
  { name: "Hallstatt, Austria", query: "hallstatt austria lake mountains" },
  { name: "Saxon Switzerland, Germany", query: "saxon switzerland germany bastion bridge" },
  { name: "Mont Saint-Michel, France", query: "mont saint michel france" },
  { name: "Geirangerfjord, Norway", query: "geirangerfjord norway" },
  { name: "Faroe Islands, Denmark", query: "faroe islands waterfall village" },
  { name: "Cliffs of Moher, Ireland", query: "cliffs of moher ireland" },
  { name: "Kirkjufell, Iceland", query: "kirkjufell mountain iceland" },
  { name: "Seceda, Italy", query: "seceda dolomites italy" },
  { name: "Lauterbrunnen, Switzerland", query: "lauterbrunnen valley switzerland" },
  { name: "Prokletije, Albania", query: "prokletije albanian alps" },
  { name: "Kotor Bay, Montenegro", query: "kotor bay montenegro" },
  { name: "Meteora, Greece", query: "meteora monasteries greece" },
  { name: "Picos de Europa, Spain", query: "picos de europa spain mountains" },
  { name: "Benagil Cave, Portugal", query: "benagil cave algarve portugal" },
  { name: "\u00c9tretat, France", query: "etretat cliffs normandy france" },
  { name: "Sveti Stefan, Montenegro", query: "sveti stefan montenegro" },
  { name: "Rila Lakes, Bulgaria", query: "seven rila lakes bulgaria" },
  {
    name: "Transf\u0103g\u0103r\u0103\u0219an, Romania",
    query: "transfagarasan road romania mountains",
  },
  { name: "\u010cesk\u00fd Krumlov, Czechia", query: "cesky krumlov czech republic" },
  { name: "Bia\u0142owie\u017ca Forest, Poland", query: "bialowieza forest poland" },
  { name: "Curonian Spit, Lithuania", query: "curonian spit lithuania dunes" },
  { name: "Gauja Valley, Latvia", query: "gauja national park latvia autumn" },
  { name: "Saaremaa, Estonia", query: "saaremaa estonia coast" },
  { name: "Lapland, Finland", query: "finnish lapland aurora cabin" },
  { name: "Abisko, Sweden", query: "abisko sweden northern lights" },
  { name: "Senja, Norway", query: "senja norway mountains ocean" },
  { name: "Giant's Causeway, United Kingdom", query: "giants causeway northern ireland" },
  { name: "Snowdonia, United Kingdom", query: "snowdonia wales mountains lake" },
  { name: "Calanques, France", query: "calanques cassis france turquoise" },
  { name: "Lake K\u00f6nigssee, Germany", query: "konigssee bavaria germany lake" },
  { name: "Grossglockner, Austria", query: "grossglockner austria alpine road" },
  { name: "So\u010da Valley, Slovenia", query: "soca river valley slovenia" },
  { name: "Hvar, Croatia", query: "hvar croatia adriatic" },
  { name: "Durmitor, Montenegro", query: "durmitor national park montenegro" },
  { name: "Mostar, Bosnia and Herzegovina", query: "mostar old bridge bosnia" },
  { name: "Ohrid, North Macedonia", query: "lake ohrid north macedonia" },
  { name: "Lofou, Cyprus", query: "lofou village cyprus stone" },
  { name: "Gozo, Malta", query: "gozo malta coast" },
  { name: "V\u00edk, Iceland", query: "vik iceland black sand beach" },
  { name: "Madeira, Portugal", query: "madeira portugal mountain coast" },
  // Asia and the Middle East
  { name: "Kyoto, Japan", query: "kyoto japan temple" },
  { name: "Petra, Jordan", query: "petra jordan treasury" },
  { name: "Zhangjiajie, China", query: "zhangjiajie china mountains" },
  { name: "Ha Long Bay, Vietnam", query: "ha long bay vietnam" },
  { name: "El Nido, Philippines", query: "el nido palawan philippines" },
  { name: "Ubud, Indonesia", query: "tegalalang rice terrace bali indonesia" },
  { name: "Mount Fuji, Japan", query: "mount fuji japan lake cherry blossoms" },
  { name: "Arashiyama, Japan", query: "arashiyama bamboo forest kyoto" },
  { name: "Shirakawa-go, Japan", query: "shirakawa go japan winter village" },
  { name: "Jeju Island, South Korea", query: "jeju island south korea coast" },
  { name: "Seoraksan, South Korea", query: "seoraksan south korea autumn" },
  { name: "Guilin, China", query: "guilin china karst li river" },
  { name: "Jiuzhaigou, China", query: "jiuzhaigou china turquoise lake" },
  { name: "Yuanyang, China", query: "yuanyang rice terraces china" },
  { name: "Tiger's Nest, Bhutan", query: "tigers nest monastery bhutan" },
  { name: "Punakha, Bhutan", query: "punakha dzong bhutan" },
  { name: "Annapurna, Nepal", query: "annapurna nepal himalaya" },
  { name: "Everest Base Camp, Nepal", query: "everest base camp nepal himalaya" },
  { name: "Pangong Lake, India", query: "pangong lake ladakh india" },
  { name: "Valley of Flowers, India", query: "valley of flowers uttarakhand india" },
  { name: "Munnar, India", query: "munnar kerala india tea plantations" },
  { name: "Hampi, India", query: "hampi india ruins landscape" },
  { name: "Sigiriya, Sri Lanka", query: "sigiriya rock sri lanka" },
  { name: "Ella, Sri Lanka", query: "ella sri lanka nine arches bridge" },
  { name: "Bagan, Myanmar", query: "bagan myanmar temples sunrise" },
  { name: "Inle Lake, Myanmar", query: "inle lake myanmar" },
  { name: "Luang Prabang, Laos", query: "luang prabang laos waterfall" },
  { name: "Angkor Wat, Cambodia", query: "angkor wat cambodia sunrise" },
  { name: "Ninh B\u00ecnh, Vietnam", query: "ninh binh vietnam limestone river" },
  { name: "H\u1ed9i An, Vietnam", query: "hoi an vietnam lanterns" },
  { name: "Khao Sok, Thailand", query: "khao sok thailand lake limestone" },
  { name: "Railay Beach, Thailand", query: "railay beach thailand cliffs" },
  { name: "Komodo, Indonesia", query: "komodo island indonesia pink beach" },
  { name: "Mount Bromo, Indonesia", query: "mount bromo indonesia sunrise" },
  { name: "Raja Ampat, Indonesia", query: "raja ampat indonesia islands" },
  { name: "Banaue, Philippines", query: "banaue rice terraces philippines" },
  { name: "Chocolate Hills, Philippines", query: "chocolate hills bohol philippines" },
  { name: "Mount Kinabalu, Malaysia", query: "mount kinabalu malaysia" },
  { name: "Cameron Highlands, Malaysia", query: "cameron highlands malaysia tea" },
  { name: "Gardens by the Bay, Singapore", query: "gardens by the bay singapore night" },
  { name: "Wadi Rum, Jordan", query: "wadi rum jordan desert" },
  { name: "Socotra, Yemen", query: "socotra yemen dragon blood trees" },
  { name: "Musandam, Oman", query: "musandam oman fjords" },
  { name: "AlUla, Saudi Arabia", query: "alula saudi arabia desert rocks" },
  { name: "Sheikh Zayed Mosque, United Arab Emirates", query: "sheikh zayed mosque abu dhabi" },
  { name: "Hormuz Island, Iran", query: "hormuz island iran colorful mountains" },
  { name: "Cappadocia Valleys, T\u00fcrkiye", query: "cappadocia turkey rock formations sunrise" },
  { name: "Lake Sevan, Armenia", query: "lake sevan armenia monastery" },
  { name: "Kazbegi, Georgia", query: "kazbegi georgia caucasus church" },
  { name: "Gobustan, Azerbaijan", query: "gobustan azerbaijan mud volcano" },
  { name: "Charyn Canyon, Kazakhstan", query: "charyn canyon kazakhstan" },
  { name: "Song-Kul, Kyrgyzstan", query: "song kul lake kyrgyzstan yurts" },
  { name: "Pamir Highway, Tajikistan", query: "pamir highway tajikistan mountains" },
  { name: "Registan, Uzbekistan", query: "registan samarkand uzbekistan" },
  { name: "Darvaza, Turkmenistan", query: "darvaza gas crater turkmenistan" },
  { name: "Gobi Desert, Mongolia", query: "gobi desert mongolia dunes camels" },
  { name: "Altai Mountains, Mongolia", query: "altai mountains mongolia" },
  { name: "Tian Shan, Kyrgyzstan", query: "tian shan kyrgyzstan mountains lake" },
  { name: "Hunza Valley, Pakistan", query: "hunza valley pakistan mountains" },
  { name: "Fairy Meadows, Pakistan", query: "fairy meadows nanga parbat pakistan" },
  // Africa
  { name: "Sossusvlei, Namibia", query: "sossusvlei namibia dunes" },
  { name: "Merzouga, Morocco", query: "merzouga sahara morocco dunes" },
  { name: "Serengeti, Tanzania", query: "serengeti tanzania acacia sunset" },
  { name: "Ngorongoro, Tanzania", query: "ngorongoro crater tanzania" },
  { name: "Mount Kilimanjaro, Tanzania", query: "mount kilimanjaro tanzania" },
  { name: "Zanzibar, Tanzania", query: "zanzibar tanzania turquoise beach" },
  { name: "Maasai Mara, Kenya", query: "maasai mara kenya wildlife landscape" },
  { name: "Amboseli, Kenya", query: "amboseli kenya elephants kilimanjaro" },
  { name: "Diani Beach, Kenya", query: "diani beach kenya" },
  { name: "Bwindi Forest, Uganda", query: "bwindi forest uganda mist" },
  { name: "Volcanoes National Park, Rwanda", query: "volcanoes national park rwanda" },
  { name: "Simien Mountains, Ethiopia", query: "simien mountains ethiopia" },
  { name: "Danakil Depression, Ethiopia", query: "danakil depression ethiopia colors" },
  { name: "Lalibela, Ethiopia", query: "lalibela ethiopia rock church" },
  { name: "Okavango Delta, Botswana", query: "okavango delta botswana aerial" },
  { name: "Makgadikgadi, Botswana", query: "makgadikgadi salt pans botswana" },
  { name: "Victoria Falls, Zimbabwe", query: "victoria falls zimbabwe" },
  { name: "Mana Pools, Zimbabwe", query: "mana pools zimbabwe elephants" },
  { name: "Blyde River Canyon, South Africa", query: "blyde river canyon south africa" },
  { name: "Drakensberg, South Africa", query: "drakensberg south africa mountains" },
  { name: "Cape Point, South Africa", query: "cape point south africa coast" },
  { name: "Namaqualand, South Africa", query: "namaqualand south africa flowers" },
  { name: "Bazaruto, Mozambique", query: "bazaruto mozambique islands" },
  { name: "Avenue of the Baobabs, Madagascar", query: "avenue of baobabs madagascar" },
  { name: "Tsingy de Bemaraha, Madagascar", query: "tsingy de bemaraha madagascar" },
  { name: "Le Morne, Mauritius", query: "le morne mauritius aerial" },
  { name: "Anse Source d'Argent, Seychelles", query: "anse source argent seychelles" },
  { name: "Pico do Fogo, Cabo Verde", query: "pico do fogo cape verde volcano" },
  { name: "Chefchaouen, Morocco", query: "chefchaouen morocco blue city" },
  { name: "Atlas Mountains, Morocco", query: "atlas mountains morocco village" },
  // North America, Central America, and the Caribbean
  { name: "Moraine Lake, Canada", query: "moraine lake banff canada" },
  { name: "Arenal, Costa Rica", query: "arenal volcano costa rica" },
  { name: "Yosemite Valley, United States", query: "yosemite valley california" },
  { name: "Grand Canyon, United States", query: "grand canyon arizona sunrise" },
  { name: "Monument Valley, United States", query: "monument valley arizona utah" },
  { name: "Na Pali Coast, United States", query: "na pali coast kauai hawaii" },
  { name: "Denali, United States", query: "denali alaska mountain" },
  { name: "Glacier Bay, United States", query: "glacier bay alaska" },
  { name: "Antelope Canyon, United States", query: "antelope canyon arizona light" },
  { name: "Maroon Bells, United States", query: "maroon bells colorado autumn" },
  { name: "Yellowstone, United States", query: "yellowstone grand prismatic spring" },
  { name: "Big Sur, United States", query: "big sur california coast" },
  { name: "Mount Rainier, United States", query: "mount rainier washington wildflowers" },
  { name: "Crater Lake, United States", query: "crater lake oregon" },
  { name: "Bryce Canyon, United States", query: "bryce canyon utah sunrise" },
  { name: "Banff, Canada", query: "banff canada mountains lake" },
  { name: "Jasper, Canada", query: "jasper national park canada" },
  { name: "Tofino, Canada", query: "tofino vancouver island canada" },
  { name: "Gros Morne, Canada", query: "gros morne newfoundland canada" },
  { name: "Torngat Mountains, Canada", query: "torngat mountains canada" },
  { name: "Tulum, Mexico", query: "tulum mexico ruins turquoise sea" },
  { name: "Sumidero Canyon, Mexico", query: "sumidero canyon chiapas mexico" },
  { name: "Hierve el Agua, Mexico", query: "hierve el agua oaxaca mexico" },
  { name: "Lake Atitl\u00e1n, Guatemala", query: "lake atitlan guatemala volcano" },
  { name: "Semuc Champey, Guatemala", query: "semuc champey guatemala pools" },
  { name: "Great Blue Hole, Belize", query: "great blue hole belize aerial" },
  { name: "Roat\u00e1n, Honduras", query: "roatan honduras reef beach" },
  { name: "Cerro Negro, Nicaragua", query: "cerro negro volcano nicaragua" },
  { name: "Monteverde, Costa Rica", query: "monteverde cloud forest costa rica" },
  { name: "Bocas del Toro, Panama", query: "bocas del toro panama islands" },
  { name: "Vi\u00f1ales, Cuba", query: "vinales cuba valley" },
  { name: "Saman\u00e1, Dominican Republic", query: "samana dominican republic coast" },
  { name: "El Yunque, Puerto Rico", query: "el yunque puerto rico rainforest" },
  { name: "Pitons, Saint Lucia", query: "pitons saint lucia" },
  { name: "The Baths, British Virgin Islands", query: "the baths virgin gorda" },
  // South America
  { name: "Torres del Paine, Chile", query: "torres del paine patagonia chile" },
  { name: "Machu Picchu, Peru", query: "machu picchu peru" },
  { name: "Iguazu Falls, Argentina", query: "iguazu falls argentina" },
  { name: "Salar de Uyuni, Bolivia", query: "salar de uyuni bolivia reflection" },
  { name: "Len\u00e7\u00f3is Maranhenses, Brazil", query: "lencois maranhenses brazil lagoons" },
  { name: "Rio de Janeiro, Brazil", query: "rio de janeiro brazil sugarloaf" },
  { name: "Chapada Diamantina, Brazil", query: "chapada diamantina brazil" },
  { name: "Fernando de Noronha, Brazil", query: "fernando de noronha brazil aerial" },
  { name: "Mount Roraima, Venezuela", query: "mount roraima venezuela" },
  { name: "Angel Falls, Venezuela", query: "angel falls venezuela" },
  { name: "Cocora Valley, Colombia", query: "cocora valley colombia wax palms" },
  { name: "Ca\u00f1o Cristales, Colombia", query: "cano cristales colombia river" },
  { name: "Gal\u00e1pagos, Ecuador", query: "galapagos ecuador landscape" },
  { name: "Cotopaxi, Ecuador", query: "cotopaxi ecuador volcano" },
  { name: "Huacachina, Peru", query: "huacachina peru oasis dunes" },
  { name: "Rainbow Mountain, Peru", query: "rainbow mountain peru" },
  { name: "Laguna Colorada, Bolivia", query: "laguna colorada bolivia flamingos" },
  { name: "Atacama Desert, Chile", query: "atacama desert chile night sky" },
  { name: "Marble Caves, Chile", query: "marble caves patagonia chile" },
  { name: "Perito Moreno, Argentina", query: "perito moreno glacier argentina" },
  { name: "Fitz Roy, Argentina", query: "fitz roy patagonia argentina" },
  { name: "Punta del Este, Uruguay", query: "punta del este uruguay coast" },
  { name: "Kaieteur Falls, Guyana", query: "kaieteur falls guyana" },
  { name: "Central Suriname Reserve, Suriname", query: "suriname rainforest river" },
  { name: "Los Roques, Venezuela", query: "los roques venezuela islands" },
  // Oceania and remote islands
  { name: "Milford Sound, New Zealand", query: "milford sound new zealand" },
  { name: "Aoraki, New Zealand", query: "aoraki mount cook new zealand" },
  { name: "Lake Tekapo, New Zealand", query: "lake tekapo new zealand lupins" },
  { name: "Tongariro, New Zealand", query: "tongariro alpine crossing new zealand" },
  { name: "Roy's Peak, New Zealand", query: "roys peak wanaka new zealand" },
  { name: "Cathedral Cove, New Zealand", query: "cathedral cove new zealand" },
  { name: "Great Barrier Reef, Australia", query: "great barrier reef australia aerial" },
  { name: "Uluru, Australia", query: "uluru australia sunset" },
  { name: "Twelve Apostles, Australia", query: "twelve apostles australia coast" },
  { name: "Whitehaven Beach, Australia", query: "whitehaven beach australia aerial" },
  { name: "Cradle Mountain, Australia", query: "cradle mountain tasmania australia" },
  { name: "Kakadu, Australia", query: "kakadu australia wetlands" },
  { name: "Bora Bora, French Polynesia", query: "bora bora french polynesia aerial" },
  { name: "Moorea, French Polynesia", query: "moorea french polynesia mountains" },
  { name: "Aitutaki, Cook Islands", query: "aitutaki cook islands lagoon" },
  { name: "Yasawa Islands, Fiji", query: "yasawa islands fiji" },
  { name: "Savai'i, Samoa", query: "savaii samoa waterfall coast" },
  { name: "Vava\u02bbu, Tonga", query: "vavau tonga islands" },
  { name: "Espiritu Santo, Vanuatu", query: "espiritu santo vanuatu blue hole" },
  { name: "Rock Islands, Palau", query: "rock islands palau aerial" },
  { name: "Kokoda Track, Papua New Guinea", query: "kokoda track papua new guinea mountains" },
  { name: "Easter Island, Chile", query: "easter island chile moai" },
  { name: "Lord Howe Island, Australia", query: "lord howe island australia" },
  { name: "Norfolk Island, Australia", query: "norfolk island australia coast" },
  // Extra world places — more Unsplash hits so threads repeat less.
  { name: "Cinque Terre, Italy", query: "cinque terre italy coast" },
  { name: "Positano, Italy", query: "positano amalfi coast italy" },
  { name: "Val d'Orcia, Italy", query: "val d orcia tuscany cypress" },
  { name: "Venice, Italy", query: "venice italy canal sunrise" },
  { name: "Lake Como, Italy", query: "lake como italy village mountains" },
  { name: "Passo Giau, Italy", query: "passo giau dolomites italy" },
  { name: "Preikestolen, Norway", query: "preikestolen pulpit rock norway" },
  { name: "Trolltunga, Norway", query: "trolltunga norway" },
  { name: "Troms\u00f8, Norway", query: "tromso norway arctic fjord" },
  { name: "Jotunheimen, Norway", query: "jotunheimen norway mountains" },
  { name: "Svalbard, Norway", query: "svalbard norway glacier arctic" },
  { name: "Glencoe, United Kingdom", query: "glencoe scotland mountains" },
  { name: "Glenfinnan, United Kingdom", query: "glenfinnan viaduct scotland" },
  { name: "Ring of Kerry, Ireland", query: "ring of kerry ireland coast" },
  { name: "Skellig Michael, Ireland", query: "skellig michael ireland" },
  { name: "M\u00f8ns Klint, Denmark", query: "mons klint denmark cliffs" },
  { name: "Koli, Finland", query: "koli national park finland lake" },
  { name: "R\u00fcgen, Germany", query: "rugen germany chalk cliffs" },
  { name: "Rhine Valley, Germany", query: "rhine valley germany castle" },
  { name: "Black Forest, Germany", query: "black forest germany hills mist" },
  { name: "Verdon Gorge, France", query: "verdon gorge france turquoise" },
  { name: "Annecy, France", query: "annecy france lake mountains" },
  { name: "Chamonix, France", query: "chamonix mont blanc france" },
  { name: "Provence, France", query: "provence france lavender fields" },
  { name: "Calanques de Piana, France", query: "calanques de piana corsica" },
  { name: "Douro Valley, Portugal", query: "douro valley portugal terraces" },
  { name: "Pico Island, Portugal", query: "pico island azores portugal" },
  { name: "Teide, Spain", query: "mount teide tenerife spain" },
  { name: "Ronda, Spain", query: "ronda spain gorge bridge" },
  { name: "Gaztelugatxe, Spain", query: "san juan gaztelugatxe spain" },
  { name: "Serra de Tramuntana, Spain", query: "serra de tramuntana mallorca" },
  { name: "Navagio, Greece", query: "navagio shipwreck beach zakynthos" },
  { name: "Zagori, Greece", query: "zagori greece stone villages" },
  { name: "Dubrovnik, Croatia", query: "dubrovnik croatia walls adriatic" },
  { name: "Krka, Croatia", query: "krka waterfalls croatia" },
  { name: "Prague, Czechia", query: "prague czech republic charles bridge" },
  { name: "Bohemian Switzerland, Czechia", query: "bohemian switzerland czech pravcicka" },
  { name: "Budapest, Hungary", query: "budapest hungary parliament danube" },
  { name: "High Tatras, Slovakia", query: "high tatras slovakia mountains lake" },
  { name: "Tatra Mountains, Poland", query: "tatra mountains poland zakopane" },
  { name: "Transylvania, Romania", query: "transylvania romania carpathian" },
  { name: "Theth, Albania", query: "theth albania alps valley" },
  { name: "Albanian Riviera, Albania", query: "albanian riviera beach mountains" },
  { name: "Bruges, Belgium", query: "bruges belgium canal" },
  { name: "Giethoorn, Netherlands", query: "giethoorn netherlands canals" },
  { name: "Mullerthal, Luxembourg", query: "mullerthal luxembourg rock forest" },
  { name: "Grindelwald, Switzerland", query: "grindelwald switzerland eiger" },
  { name: "Oeschinen Lake, Switzerland", query: "oeschinen lake switzerland" },
  { name: "Mount Etna, Italy", query: "mount etna sicily italy" },
  { name: "Stromboli, Italy", query: "stromboli italy volcano" },
  { name: "Sapa, Vietnam", query: "sapa vietnam rice terraces mist" },
  { name: "Nusa Penida, Indonesia", query: "nusa penida indonesia cliffs" },
  { name: "Coron, Philippines", query: "coron palawan philippines lagoons" },
  { name: "Kelimutu, Indonesia", query: "kelimutu indonesia colored lakes" },
  { name: "Taroko Gorge, Taiwan", query: "taroko gorge taiwan" },
  { name: "Sun Moon Lake, Taiwan", query: "sun moon lake taiwan" },
  { name: "Alishan, Taiwan", query: "alishan taiwan forest sunrise" },
  { name: "Boseong, South Korea", query: "boseong tea fields south korea" },
  { name: "Kamikochi, Japan", query: "kamikochi japan alps" },
  { name: "Biei, Japan", query: "biei hokkaido japan blue pond" },
  { name: "Furano, Japan", query: "furano hokkaido lavender" },
  { name: "Hakone, Japan", query: "hakone japan mount fuji lake" },
  { name: "Shiretoko, Japan", query: "shiretoko hokkaido japan" },
  { name: "Takachiho, Japan", query: "takachiho gorge japan" },
  { name: "Okinawa, Japan", query: "okinawa japan turquoise coast" },
  { name: "Dal Lake, India", query: "dal lake srinagar kashmir" },
  { name: "Jaisalmer, India", query: "jaisalmer india thar desert fort" },
  { name: "Rann of Kutch, India", query: "rann of kutch india white desert" },
  { name: "Andaman Islands, India", query: "andaman islands india beach" },
  { name: "Maldives", query: "maldives aerial atoll turquoise" },
  { name: "Pamukkale, T\u00fcrkiye", query: "pamukkale turkey white terraces" },
  { name: "Svaneti, Georgia", query: "svaneti georgia towers mountains" },
  { name: "Cedars of God, Lebanon", query: "cedars of god lebanon" },
  { name: "Dead Sea, Jordan", query: "dead sea jordan coastline" },
  { name: "Isfahan, Iran", query: "isfahan iran mosque square" },
  { name: "Tigray, Ethiopia", query: "tigray ethiopia rock churches landscape" },
  { name: "Fish River Canyon, Namibia", query: "fish river canyon namibia" },
  { name: "Skeleton Coast, Namibia", query: "skeleton coast namibia dunes ocean" },
  { name: "Table Mountain, South Africa", query: "table mountain cape town south africa" },
  { name: "Spitzkoppe, Namibia", query: "spitzkoppe namibia granite" },
  { name: "Lake Malawi, Malawi", query: "lake malawi africa shoreline" },
  { name: "Virunga, Democratic Republic of the Congo", query: "virunga volcanoes congo" },
  { name: "White Sands, United States", query: "white sands new mexico dunes" },
  { name: "Zion, United States", query: "zion national park utah" },
  { name: "Arches, United States", query: "delicate arch utah sunset" },
  { name: "Canyonlands, United States", query: "canyonlands utah mesa arch" },
  { name: "Death Valley, United States", query: "death valley california dunes" },
  { name: "Olympic Peninsula, United States", query: "olympic national park washington moss" },
  { name: "Acadia, United States", query: "acadia maine coast sunrise" },
  { name: "Grand Teton, United States", query: "grand teton wyoming snake river" },
  { name: "Great Smoky Mountains, United States", query: "great smoky mountains mist" },
  { name: "Sedona, United States", query: "sedona arizona red rocks" },
  { name: "Havasu Falls, United States", query: "havasu falls arizona" },
  { name: "Multnomah Falls, United States", query: "multnomah falls oregon" },
  { name: "Antelope Island, United States", query: "great salt lake utah" },
  { name: "Lake Louise, Canada", query: "lake louise banff canada" },
  { name: "Peyto Lake, Canada", query: "peyto lake banff canada" },
  { name: "Niagara, Canada", query: "niagara falls canada aerial" },
  { name: "Bay of Fundy, Canada", query: "bay of fundy canada" },
  { name: "Saguenay Fjord, Canada", query: "saguenay fjord canada" },
  { name: "Copper Canyon, Mexico", query: "copper canyon mexico" },
  { name: "Pe\u00f1a de Bernal, Mexico", query: "pena de bernal mexico" },
  { name: "Salar de Atacama, Chile", query: "salar de atacama chile lagoon" },
  { name: "Quebrada de Humahuaca, Argentina", query: "quebrada de humahuaca argentina" },
  { name: "Iguazu Brazilian Side, Brazil", query: "iguazu falls brazil aerial" },
  { name: "Jalap\u00e3o, Brazil", query: "jalapao tocantins brazil dunes" },
  { name: "Ushuaia, Argentina", query: "ushuaia argentina mountains" },
  { name: "Hooker Valley, New Zealand", query: "hooker valley mount cook new zealand" },
  { name: "Doubtful Sound, New Zealand", query: "doubtful sound new zealand" },
  { name: "Mount Aspiring, New Zealand", query: "mount aspiring new zealand" },
  { name: "Punakaiki, New Zealand", query: "punakaiki pancake rocks new zealand" },
  { name: "Bay of Islands, New Zealand", query: "bay of islands new zealand" },
  { name: "Wilsons Promontory, Australia", query: "wilsons promontory australia" },
  { name: "Blue Mountains, Australia", query: "blue mountains australia three sisters" },
  { name: "The Pinnacles, Australia", query: "pinnacles desert western australia" },
  { name: "Ningaloo, Australia", query: "ningaloo reef australia aerial" },
  { name: "Bay of Fires, Australia", query: "bay of fires tasmania" },
  { name: "Fiordland, New Zealand", query: "fiordland new zealand waterfall" },
  { name: "Antarctica Peninsula", query: "antarctica peninsula icebergs" },
  { name: "South Georgia", query: "south georgia island landscape" },
  { name: "Greenland Ilulissat", query: "ilulissat icefjord greenland" },
  { name: "Kalsoy, Faroe Islands", query: "kalsoy lighthouse faroe islands" },
];

export const NIGHT_CITIES_CATALOG: ReadonlyArray<SceneryLocation> = [
  { name: "Shinjuku, Japan", query: "tokyo shinjuku neon night" },
  { name: "Shibuya, Japan", query: "shibuya crossing tokyo night" },
  { name: "Dotonbori, Japan", query: "osaka dotonbori night neon" },
  { name: "Hong Kong Island, China", query: "hong kong skyline night victoria harbour" },
  { name: "Mong Kok, China", query: "hong kong neon rain night street" },
  { name: "The Bund, China", query: "shanghai bund night skyline" },
  { name: "Pudong, China", query: "shanghai pudong night rain" },
  { name: "Seoul, South Korea", query: "seoul night skyline namsan" },
  { name: "Myeongdong, South Korea", query: "seoul myeongdong night rain neon" },
  { name: "Marina Bay, Singapore", query: "singapore marina bay night" },
  { name: "Times Square, United States", query: "times square new york night" },
  { name: "Brooklyn Bridge, United States", query: "brooklyn bridge new york night" },
  { name: "Manhattan, United States", query: "manhattan skyline night rain" },
  { name: "Chicago River, United States", query: "chicago skyline night river" },
  { name: "San Francisco, United States", query: "san francisco night fog skyline" },
  { name: "Los Angeles, United States", query: "los angeles downtown night" },
  { name: "Las Vegas, United States", query: "las vegas strip night" },
  { name: "Miami, United States", query: "miami skyline night" },
  { name: "Seattle, United States", query: "seattle skyline night" },
  { name: "Portland Rain, United States", query: "portland oregon rain night street" },
  { name: "London, United Kingdom", query: "london thames night skyline" },
  { name: "Paris, France", query: "paris eiffel tower night" },
  { name: "Berlin, Germany", query: "berlin night skyline" },
  { name: "Amsterdam, Netherlands", query: "amsterdam canals night" },
  { name: "Barcelona, Spain", query: "barcelona night skyline" },
  { name: "Prague Night, Czechia", query: "prague night charles bridge" },
  { name: "Budapest Night, Hungary", query: "budapest parliament night" },
  { name: "Vienna, Austria", query: "vienna night city" },
  { name: "Istanbul, T\u00fcrkiye", query: "istanbul night galata" },
  { name: "Dubai, United Arab Emirates", query: "dubai skyline night" },
  { name: "Sydney, Australia", query: "sydney harbour night opera house" },
  { name: "Melbourne, Australia", query: "melbourne night city rain" },
  { name: "Toronto, Canada", query: "toronto skyline night" },
  { name: "Vancouver, Canada", query: "vancouver night skyline mountains" },
  { name: "Montreal, Canada", query: "montreal night old city" },
  { name: "Mexico City, Mexico", query: "mexico city night skyline" },
  { name: "S\u00e3o Paulo, Brazil", query: "sao paulo night skyline" },
  { name: "Rio Night, Brazil", query: "rio de janeiro night skyline" },
  { name: "Buenos Aires, Argentina", query: "buenos aires night city" },
  { name: "Bangkok, Thailand", query: "bangkok night skyline river" },
  { name: "Taipei, Taiwan", query: "taipei 101 night skyline" },
  { name: "Kuala Lumpur, Malaysia", query: "kuala lumpur petronas night" },
  { name: "Mumbai, India", query: "mumbai night skyline marine drive" },
  { name: "Cape Town, South Africa", query: "cape town night waterfront" },
  { name: "Cairo, Egypt", query: "cairo night city nile" },
  { name: "Moscow, Russia", query: "moscow night red square" },
  { name: "St. Petersburg, Russia", query: "saint petersburg night palace" },
  { name: "Tokyo Rain, Japan", query: "tokyo rain night street neon" },
  { name: "New York Rain, United States", query: "new york rain night street reflections" },
  { name: "Chicago Rain, United States", query: "chicago rain night street" },
];

export const DEEP_FOREST_CATALOG: ReadonlyArray<SceneryLocation> = [
  { name: "Redwood National Park, United States", query: "redwood forest california fog" },
  { name: "Hoh Rain Forest, United States", query: "hoh rainforest olympic moss" },
  { name: "Olympic Peninsula Woods, United States", query: "olympic national park mossy forest" },
  { name: "Sequoia Grove, United States", query: "sequoia grove fog california" },
  { name: "Great Smoky Mountains Woods, United States", query: "smoky mountains forest mist" },
  { name: "Appalachian Forest, United States", query: "appalachian forest autumn mist" },
  { name: "Tongass, United States", query: "tongass national forest alaska" },
  { name: "Yakushima, Japan", query: "yakushima japan moss cedar forest" },
  { name: "Shirakami, Japan", query: "shirakami sanchi japan beech forest" },
  { name: "Kamikochi Woods, Japan", query: "kamikochi japan forest river" },
  { name: "Black Forest Woods, Germany", query: "black forest germany fog trees" },
  { name: "Bavarian Forest, Germany", query: "bavarian forest germany mist" },
  { name: "Bia\u0142owie\u017ca Woods, Poland", query: "bialowieza forest mist trees" },
  { name: "Carpathian Forest, Romania", query: "carpathian forest romania mist" },
  { name: "Caledonian Forest, United Kingdom", query: "caledonian forest scotland pine" },
  { name: "Ancient Woodland, United Kingdom", query: "ancient woodland england bluebells" },
  { name: "Irati Forest, Spain", query: "irati forest spain beech" },
  { name: "Fontainebleau, France", query: "fontainebleau forest france" },
  { name: "Ardennes, Belgium", query: "ardennes forest mist" },
  { name: "Taiga, Finland", query: "finnish taiga pine forest mist" },
  { name: "Siberian Taiga, Russia", query: "siberian taiga forest" },
  { name: "Daintree, Australia", query: "daintree rainforest australia" },
  { name: "Tarkine, Australia", query: "tarkine forest tasmania" },
  { name: "Waipoua, New Zealand", query: "waipoua kauri forest new zealand" },
  { name: "Fiordland Forest, New Zealand", query: "fiordland rainforest new zealand" },
  { name: "Amazon Rainforest, Brazil", query: "amazon rainforest river canopy" },
  { name: "Valdivian Forest, Chile", query: "valdivian rainforest chile" },
  { name: "Andean Cloud Forest, Ecuador", query: "andean cloud forest ecuador" },
  { name: "Monteverde Woods, Costa Rica", query: "monteverde cloud forest mist" },
  { name: "Borneo Rainforest, Malaysia", query: "borneo rainforest mist" },
  { name: "Mossy Forest, Malaysia", query: "mossy forest cameron highlands" },
  { name: "Sinharaja, Sri Lanka", query: "sinharaja rainforest sri lanka" },
  { name: "Sumatra Rainforest, Indonesia", query: "sumatra rainforest indonesia" },
  { name: "Madagascar Forest, Madagascar", query: "madagascar rainforest mist" },
  { name: "Congo Basin, Republic of the Congo", query: "congo basin rainforest" },
  { name: "Bwindi Woods, Uganda", query: "bwindi forest mist uganda" },
  { name: "Cedar Forest, Morocco", query: "atlas cedar forest morocco mist" },
  { name: "Pacific Northwest, Canada", query: "british columbia rainforest moss" },
  { name: "Great Bear Rainforest, Canada", query: "great bear rainforest canada" },
  { name: "Fundy Forest, Canada", query: "bay of fundy forest fog" },
  { name: "Patagonian Woods, Chile", query: "patagonia forest mist lenga" },
  { name: "Jiuzhaigou Woods, China", query: "jiuzhaigou forest lake china" },
  { name: "Zhangjiajie Forest, China", query: "zhangjiajie forest pillars mist" },
  { name: "Plitvice Woods, Croatia", query: "plitvice forest waterfall moss" },
  { name: "Slovenian Forest, Slovenia", query: "slovenia forest mist river" },
  { name: "Hallstatt Woods, Austria", query: "austrian alpine forest mist" },
  { name: "Swiss Forest, Switzerland", query: "swiss forest mist pine" },
  { name: "Norwegian Forest, Norway", query: "norway pine forest fjord mist" },
  { name: "Hokkaido Forest, Japan", query: "hokkaido forest autumn mist" },
];

export const NIGHT_SKY_CATALOG: ReadonlyArray<SceneryLocation> = [
  { name: "Lofoten Aurora, Norway", query: "lofoten norway aurora borealis" },
  { name: "Troms\u00f8 Aurora, Norway", query: "tromso aurora borealis night" },
  { name: "Abisko Aurora, Sweden", query: "abisko sweden northern lights" },
  { name: "Lapland Aurora, Finland", query: "finnish lapland aurora cabin" },
  { name: "Iceland Aurora, Iceland", query: "iceland aurora borealis landscape" },
  { name: "Yukon Aurora, Canada", query: "yukon canada northern lights" },
  { name: "Yellowknife Aurora, Canada", query: "yellowknife aurora borealis" },
  { name: "Alaska Aurora, United States", query: "alaska aurora borealis mountains" },
  { name: "Atacama Sky, Chile", query: "atacama desert milky way" },
  { name: "Namib Sky, Namibia", query: "namibia desert milky way" },
  { name: "Wadi Rum Sky, Jordan", query: "wadi rum milky way night" },
  { name: "Sahara Sky, Morocco", query: "sahara morocco milky way dunes" },
  { name: "Aoraki Sky, New Zealand", query: "aoraki mount cook milky way" },
  { name: "Tekapo Sky, New Zealand", query: "lake tekapo milky way" },
  { name: "Uluru Sky, Australia", query: "uluru milky way night" },
  { name: "Death Valley Sky, United States", query: "death valley milky way" },
  { name: "Big Bend Sky, United States", query: "big bend texas milky way" },
  { name: "Utah Sky, United States", query: "utah desert milky way arches" },
  { name: "Yosemite Sky, United States", query: "yosemite milky way night" },
  { name: "Grand Canyon Sky, United States", query: "grand canyon milky way" },
  { name: "Monument Valley Sky, United States", query: "monument valley milky way" },
  { name: "Jasper Sky, Canada", query: "jasper dark sky milky way" },
  { name: "Mauna Kea, United States", query: "mauna kea hawaii milky way" },
  { name: "Canary Islands Sky, Spain", query: "la palma milky way observatory" },
  { name: "Alps Sky, Switzerland", query: "swiss alps milky way" },
  { name: "Dolomites Sky, Italy", query: "dolomites milky way night" },
  { name: "Himalaya Sky, Nepal", query: "himalaya milky way night" },
  { name: "Andes Sky, Peru", query: "andes peru milky way" },
  { name: "Patagonia Sky, Argentina", query: "patagonia milky way fitz roy" },
  { name: "Salar Sky, Bolivia", query: "salar de uyuni milky way" },
  { name: "Iceland Stars, Iceland", query: "iceland milky way kirkjufell" },
  { name: "Norway Stars, Norway", query: "norway fjord milky way" },
  { name: "Meteor Shower, United States", query: "perseid meteor shower landscape" },
  { name: "Star Trails, United States", query: "star trails desert landscape" },
  { name: "Moonrise Mountains, United States", query: "full moon mountain landscape night" },
  { name: "Airglow, New Zealand", query: "airglow milky way night landscape" },
  { name: "Zodiacal Light, Chile", query: "zodiacal light desert night" },
  { name: "Green Aurora, Iceland", query: "green aurora over mountains" },
  { name: "Purple Aurora, Norway", query: "purple aurora borealis night" },
  { name: "Aurora Lake, Canada", query: "aurora borealis lake reflection" },
  { name: "Dark Sky Park, United States", query: "international dark sky park milky way" },
  { name: "Pic du Midi, France", query: "pic du midi milky way" },
  { name: "Namib Dunes Sky, Namibia", query: "sossusvlei milky way dunes" },
  { name: "Gobi Sky, Mongolia", query: "gobi desert milky way" },
  { name: "Tibet Sky, China", query: "tibet milky way mountains" },
];

export const GRAND_BUILDINGS_CATALOG: ReadonlyArray<SceneryLocation> = [
  { name: "Sagrada Fam\u00edlia, Spain", query: "sagrada familia barcelona architecture" },
  { name: "Alhambra, Spain", query: "alhambra granada architecture" },
  { name: "Duomo di Milano, Italy", query: "milan duomo cathedral architecture" },
  { name: "Florence Cathedral, Italy", query: "florence duomo architecture" },
  { name: "St. Peter's Basilica, Italy", query: "st peters basilica vatican architecture" },
  { name: "Pantheon, Italy", query: "pantheon rome architecture" },
  { name: "Colosseum, Italy", query: "colosseum rome architecture" },
  { name: "Notre-Dame, France", query: "notre dame paris cathedral architecture" },
  { name: "Sainte-Chapelle, France", query: "sainte chapelle paris stained glass" },
  { name: "Mont-Saint-Michel Abbey, France", query: "mont saint michel abbey architecture" },
  { name: "Cologne Cathedral, Germany", query: "cologne cathedral architecture" },
  { name: "Neuschwanstein, Germany", query: "neuschwanstein castle architecture" },
  { name: "St. Basil's, Russia", query: "st basils cathedral moscow architecture" },
  { name: "Hagia Sophia, T\u00fcrkiye", query: "hagia sophia istanbul architecture" },
  { name: "Blue Mosque, T\u00fcrkiye", query: "blue mosque istanbul architecture" },
  { name: "Taj Mahal, India", query: "taj mahal agra architecture" },
  { name: "Golden Temple, India", query: "golden temple amritsar architecture" },
  { name: "Meenakshi Temple, India", query: "meenakshi temple madurai architecture" },
  { name: "Lotus Temple, India", query: "lotus temple delhi architecture" },
  { name: "Angkor Wat, Cambodia", query: "angkor wat temple architecture" },
  { name: "Borobudur, Indonesia", query: "borobudur temple architecture" },
  { name: "Prambanan, Indonesia", query: "prambanan temple architecture" },
  { name: "Wat Arun, Thailand", query: "wat arun bangkok architecture" },
  { name: "Kiyomizu-dera, Japan", query: "kiyomizu dera kyoto architecture" },
  { name: "T\u014ddai-ji, Japan", query: "todaiji nara architecture" },
  { name: "By\u014dd\u014d-in, Japan", query: "byodoin uji architecture" },
  { name: "Forbidden City, China", query: "forbidden city beijing architecture" },
  { name: "Temple of Heaven, China", query: "temple of heaven beijing architecture" },
  { name: "Sheikh Zayed Mosque, United Arab Emirates", query: "sheikh zayed mosque architecture" },
  { name: "Hassan II Mosque, Morocco", query: "hassan ii mosque casablanca architecture" },
  { name: "Petra Treasury, Jordan", query: "petra treasury architecture" },
  { name: "Parthenon, Greece", query: "parthenon athens architecture" },
  { name: "Westminster, United Kingdom", query: "westminster palace london architecture" },
  { name: "St. Paul's, United Kingdom", query: "st pauls cathedral london architecture" },
  { name: "Sagrada Interior, Spain", query: "sagrada familia interior columns" },
  { name: "Casa Mil\u00e0, Spain", query: "casa mila gaudi architecture" },
  { name: "Guggenheim Bilbao, Spain", query: "guggenheim bilbao architecture" },
  { name: "Fallingwater, United States", query: "fallingwater wright architecture" },
  { name: "Chrysler Building, United States", query: "chrysler building new york architecture" },
  { name: "Flatiron, United States", query: "flatiron building new york architecture" },
  { name: "Sydney Opera House, Australia", query: "sydney opera house architecture" },
  { name: "Petronas Towers, Malaysia", query: "petronas towers architecture" },
  { name: "Burj Khalifa, United Arab Emirates", query: "burj khalifa architecture" },
  { name: "Marina Bay Sands, Singapore", query: "marina bay sands architecture" },
  { name: "Louvre, France", query: "louvre pyramid paris architecture" },
  { name: "Ch\u00e2teau de Chenonceau, France", query: "chenonceau castle architecture" },
  { name: "Versailles, France", query: "palace of versailles architecture" },
  { name: "Sch\u00f6nbrunn, Austria", query: "schonbrunn palace architecture" },
  { name: "Potala Palace, China", query: "potala palace lhasa architecture" },
  { name: "Shwedagon, Myanmar", query: "shwedagon pagoda architecture" },
];

export const PHOTO_SET_CATALOGS: Record<PhotoSetId, ReadonlyArray<SceneryLocation>> = {
  "world-scenery": WORLD_SCENERY_CATALOG,
  "night-cities": NIGHT_CITIES_CATALOG,
  "deep-forest": DEEP_FOREST_CATALOG,
  "night-sky": NIGHT_SKY_CATALOG,
  "grand-buildings": GRAND_BUILDINGS_CATALOG,
};
