/**
 * Curated, geographically diverse places used by the World scenery set.
 * Ported verbatim from SurgeCode v0.2.7 WorldSceneryCatalog.swift.
 *
 * Keep names suitable for attribution labels and queries specific enough that
 * Unsplash returns the actual place rather than a generic photo of the country.
 */
export interface SceneryLocation {
  readonly name: string;
  readonly query: string;
}

export const WORLD_SCENERY_CATALOG: ReadonlyArray<SceneryLocation> = [
  /// Curated, geographically diverse places used by the built-in World scenery set.
  ///
  /// Keep names suitable for thread titles and queries specific enough that Unsplash
  /// returns the actual place rather than a generic photo from the surrounding country.
  // Europe
  { name: "Santorini, Greece", query: "santorini greece caldera" },
  { name: "Tre Cime, Italy", query: "tre cime dolomites italy" },
  { name: "Lofoten, Norway", query: "lofoten islands norway" },
  { name: "Zermatt, Switzerland", query: "matterhorn zermatt switzerland" },
  { name: "Sk\u00f3gafoss, Iceland", query: "skogafoss waterfall iceland" },
  { name: "Cappadocia, T\u00fcrkiye", query: "cappadocia turkey balloons" },
  { name: "Plitvice Lakes, Croatia", query: "plitvice lakes croatia" },
  { name: "Isle of Skye, United Kingdom", query: "isle of skye scotland" },
  { name: "Lake Bled, Slovenia", query: "lake bled slovenia" },
  { name: "Sete Cidades, Portugal", query: "sete cidades azores portugal" },
  { name: "Hallstatt, Austria", query: "hallstatt austria lake mountains" },
  { name: "Saxon Switzerland, Germany", query: "saxon switzerland germany bastion bridge" },
  { name: "Mont Saint-Michel, France", query: "mont saint michel france" },
  { name: "Geirangerfjord, Norway", query: "geirangerfjord norway" },
  { name: "Faroe Islands, Denmark", query: "faroe islands waterfall village" },
  { name: "Cliffs of Moher, Ireland", query: "cliffs of moher ireland" },
  { name: "Kirkjufell, Iceland", query: "kirkjufell mountain iceland" },
  { name: "Seceda, Italy", query: "seceda dolomites italy" },
  { name: "Lauterbrunnen, Switzerland", query: "lauterbrunnen valley switzerland" },
  { name: "Prokletije, Albania", query: "prokletije albanian alps" },
  { name: "Kotor Bay, Montenegro", query: "kotor bay montenegro" },
  { name: "Meteora, Greece", query: "meteora monasteries greece" },
  { name: "Picos de Europa, Spain", query: "picos de europa spain mountains" },
  { name: "Benagil Cave, Portugal", query: "benagil cave algarve portugal" },
  { name: "\u00c9tretat, France", query: "etretat cliffs normandy france" },
  { name: "Sveti Stefan, Montenegro", query: "sveti stefan montenegro" },
  { name: "Rila Lakes, Bulgaria", query: "seven rila lakes bulgaria" },
  {
    name: "Transf\u0103g\u0103r\u0103\u0219an, Romania",
    query: "transfagarasan road romania mountains",
  },
  { name: "\u010cesk\u00fd Krumlov, Czechia", query: "cesky krumlov czech republic" },
  { name: "Bia\u0142owie\u017ca Forest, Poland", query: "bialowieza forest poland" },
  { name: "Curonian Spit, Lithuania", query: "curonian spit lithuania dunes" },
  { name: "Gauja Valley, Latvia", query: "gauja national park latvia autumn" },
  { name: "Saaremaa, Estonia", query: "saaremaa estonia coast" },
  { name: "Lapland, Finland", query: "finnish lapland aurora cabin" },
  { name: "Abisko, Sweden", query: "abisko sweden northern lights" },
  { name: "Senja, Norway", query: "senja norway mountains ocean" },
  { name: "Giant's Causeway, United Kingdom", query: "giants causeway northern ireland" },
  { name: "Snowdonia, United Kingdom", query: "snowdonia wales mountains lake" },
  { name: "Calanques, France", query: "calanques cassis france turquoise" },
  { name: "Lake K\u00f6nigssee, Germany", query: "konigssee bavaria germany lake" },
  { name: "Grossglockner, Austria", query: "grossglockner austria alpine road" },
  { name: "So\u010da Valley, Slovenia", query: "soca river valley slovenia" },
  { name: "Hvar, Croatia", query: "hvar croatia adriatic" },
  { name: "Durmitor, Montenegro", query: "durmitor national park montenegro" },
  { name: "Mostar, Bosnia and Herzegovina", query: "mostar old bridge bosnia" },
  { name: "Ohrid, North Macedonia", query: "lake ohrid north macedonia" },
  { name: "Lofou, Cyprus", query: "lofou village cyprus stone" },
  { name: "Gozo, Malta", query: "gozo malta coast" },
  { name: "V\u00edk, Iceland", query: "vik iceland black sand beach" },
  { name: "Madeira, Portugal", query: "madeira portugal mountain coast" },
  // Asia and the Middle East
  { name: "Kyoto, Japan", query: "kyoto japan temple" },
  { name: "Petra, Jordan", query: "petra jordan treasury" },
  { name: "Zhangjiajie, China", query: "zhangjiajie china mountains" },
  { name: "Ha Long Bay, Vietnam", query: "ha long bay vietnam" },
  { name: "El Nido, Philippines", query: "el nido palawan philippines" },
  { name: "Ubud, Indonesia", query: "tegalalang rice terrace bali indonesia" },
  { name: "Mount Fuji, Japan", query: "mount fuji japan lake cherry blossoms" },
  { name: "Arashiyama, Japan", query: "arashiyama bamboo forest kyoto" },
  { name: "Shirakawa-go, Japan", query: "shirakawa go japan winter village" },
  { name: "Jeju Island, South Korea", query: "jeju island south korea coast" },
  { name: "Seoraksan, South Korea", query: "seoraksan south korea autumn" },
  { name: "Guilin, China", query: "guilin china karst li river" },
  { name: "Jiuzhaigou, China", query: "jiuzhaigou china turquoise lake" },
  { name: "Yuanyang, China", query: "yuanyang rice terraces china" },
  { name: "Tiger's Nest, Bhutan", query: "tigers nest monastery bhutan" },
  { name: "Punakha, Bhutan", query: "punakha dzong bhutan" },
  { name: "Annapurna, Nepal", query: "annapurna nepal himalaya" },
  { name: "Everest Base Camp, Nepal", query: "everest base camp nepal himalaya" },
  { name: "Pangong Lake, India", query: "pangong lake ladakh india" },
  { name: "Valley of Flowers, India", query: "valley of flowers uttarakhand india" },
  { name: "Munnar, India", query: "munnar kerala india tea plantations" },
  { name: "Hampi, India", query: "hampi india ruins landscape" },
  { name: "Sigiriya, Sri Lanka", query: "sigiriya rock sri lanka" },
  { name: "Ella, Sri Lanka", query: "ella sri lanka nine arches bridge" },
  { name: "Bagan, Myanmar", query: "bagan myanmar temples sunrise" },
  { name: "Inle Lake, Myanmar", query: "inle lake myanmar" },
  { name: "Luang Prabang, Laos", query: "luang prabang laos waterfall" },
  { name: "Angkor Wat, Cambodia", query: "angkor wat cambodia sunrise" },
  { name: "Ninh B\u00ecnh, Vietnam", query: "ninh binh vietnam limestone river" },
  { name: "H\u1ed9i An, Vietnam", query: "hoi an vietnam lanterns" },
  { name: "Khao Sok, Thailand", query: "khao sok thailand lake limestone" },
  { name: "Railay Beach, Thailand", query: "railay beach thailand cliffs" },
  { name: "Komodo, Indonesia", query: "komodo island indonesia pink beach" },
  { name: "Mount Bromo, Indonesia", query: "mount bromo indonesia sunrise" },
  { name: "Raja Ampat, Indonesia", query: "raja ampat indonesia islands" },
  { name: "Banaue, Philippines", query: "banaue rice terraces philippines" },
  { name: "Chocolate Hills, Philippines", query: "chocolate hills bohol philippines" },
  { name: "Mount Kinabalu, Malaysia", query: "mount kinabalu malaysia" },
  { name: "Cameron Highlands, Malaysia", query: "cameron highlands malaysia tea" },
  { name: "Gardens by the Bay, Singapore", query: "gardens by the bay singapore night" },
  { name: "Wadi Rum, Jordan", query: "wadi rum jordan desert" },
  { name: "Socotra, Yemen", query: "socotra yemen dragon blood trees" },
  { name: "Musandam, Oman", query: "musandam oman fjords" },
  { name: "AlUla, Saudi Arabia", query: "alula saudi arabia desert rocks" },
  { name: "Sheikh Zayed Mosque, United Arab Emirates", query: "sheikh zayed mosque abu dhabi" },
  { name: "Hormuz Island, Iran", query: "hormuz island iran colorful mountains" },
  { name: "Cappadocia Valleys, T\u00fcrkiye", query: "cappadocia turkey rock formations sunrise" },
  { name: "Lake Sevan, Armenia", query: "lake sevan armenia monastery" },
  { name: "Kazbegi, Georgia", query: "kazbegi georgia caucasus church" },
  { name: "Gobustan, Azerbaijan", query: "gobustan azerbaijan mud volcano" },
  { name: "Charyn Canyon, Kazakhstan", query: "charyn canyon kazakhstan" },
  { name: "Song-Kul, Kyrgyzstan", query: "song kul lake kyrgyzstan yurts" },
  { name: "Pamir Highway, Tajikistan", query: "pamir highway tajikistan mountains" },
  { name: "Registan, Uzbekistan", query: "registan samarkand uzbekistan" },
  { name: "Darvaza, Turkmenistan", query: "darvaza gas crater turkmenistan" },
  { name: "Gobi Desert, Mongolia", query: "gobi desert mongolia dunes camels" },
  { name: "Altai Mountains, Mongolia", query: "altai mountains mongolia" },
  { name: "Tian Shan, Kyrgyzstan", query: "tian shan kyrgyzstan mountains lake" },
  { name: "Hunza Valley, Pakistan", query: "hunza valley pakistan mountains" },
  { name: "Fairy Meadows, Pakistan", query: "fairy meadows nanga parbat pakistan" },
  // Africa
  { name: "Sossusvlei, Namibia", query: "sossusvlei namibia dunes" },
  { name: "Merzouga, Morocco", query: "merzouga sahara morocco dunes" },
  { name: "Serengeti, Tanzania", query: "serengeti tanzania acacia sunset" },
  { name: "Ngorongoro, Tanzania", query: "ngorongoro crater tanzania" },
  { name: "Mount Kilimanjaro, Tanzania", query: "mount kilimanjaro tanzania" },
  { name: "Zanzibar, Tanzania", query: "zanzibar tanzania turquoise beach" },
  { name: "Maasai Mara, Kenya", query: "maasai mara kenya wildlife landscape" },
  { name: "Amboseli, Kenya", query: "amboseli kenya elephants kilimanjaro" },
  { name: "Diani Beach, Kenya", query: "diani beach kenya" },
  { name: "Bwindi Forest, Uganda", query: "bwindi forest uganda mist" },
  { name: "Volcanoes National Park, Rwanda", query: "volcanoes national park rwanda" },
  { name: "Simien Mountains, Ethiopia", query: "simien mountains ethiopia" },
  { name: "Danakil Depression, Ethiopia", query: "danakil depression ethiopia colors" },
  { name: "Lalibela, Ethiopia", query: "lalibela ethiopia rock church" },
  { name: "Okavango Delta, Botswana", query: "okavango delta botswana aerial" },
  { name: "Makgadikgadi, Botswana", query: "makgadikgadi salt pans botswana" },
  { name: "Victoria Falls, Zimbabwe", query: "victoria falls zimbabwe" },
  { name: "Mana Pools, Zimbabwe", query: "mana pools zimbabwe elephants" },
  { name: "Blyde River Canyon, South Africa", query: "blyde river canyon south africa" },
  { name: "Drakensberg, South Africa", query: "drakensberg south africa mountains" },
  { name: "Cape Point, South Africa", query: "cape point south africa coast" },
  { name: "Namaqualand, South Africa", query: "namaqualand south africa flowers" },
  { name: "Bazaruto, Mozambique", query: "bazaruto mozambique islands" },
  { name: "Avenue of the Baobabs, Madagascar", query: "avenue of baobabs madagascar" },
  { name: "Tsingy de Bemaraha, Madagascar", query: "tsingy de bemaraha madagascar" },
  { name: "Le Morne, Mauritius", query: "le morne mauritius aerial" },
  { name: "Anse Source d'Argent, Seychelles", query: "anse source argent seychelles" },
  { name: "Pico do Fogo, Cabo Verde", query: "pico do fogo cape verde volcano" },
  { name: "Chefchaouen, Morocco", query: "chefchaouen morocco blue city" },
  { name: "Atlas Mountains, Morocco", query: "atlas mountains morocco village" },
  // North America, Central America, and the Caribbean
  { name: "Moraine Lake, Canada", query: "moraine lake banff canada" },
  { name: "Arenal, Costa Rica", query: "arenal volcano costa rica" },
  { name: "Yosemite Valley, United States", query: "yosemite valley california" },
  { name: "Grand Canyon, United States", query: "grand canyon arizona sunrise" },
  { name: "Monument Valley, United States", query: "monument valley arizona utah" },
  { name: "Na Pali Coast, United States", query: "na pali coast kauai hawaii" },
  { name: "Denali, United States", query: "denali alaska mountain" },
  { name: "Glacier Bay, United States", query: "glacier bay alaska" },
  { name: "Antelope Canyon, United States", query: "antelope canyon arizona light" },
  { name: "Maroon Bells, United States", query: "maroon bells colorado autumn" },
  { name: "Yellowstone, United States", query: "yellowstone grand prismatic spring" },
  { name: "Big Sur, United States", query: "big sur california coast" },
  { name: "Mount Rainier, United States", query: "mount rainier washington wildflowers" },
  { name: "Crater Lake, United States", query: "crater lake oregon" },
  { name: "Bryce Canyon, United States", query: "bryce canyon utah sunrise" },
  { name: "Banff, Canada", query: "banff canada mountains lake" },
  { name: "Jasper, Canada", query: "jasper national park canada" },
  { name: "Tofino, Canada", query: "tofino vancouver island canada" },
  { name: "Gros Morne, Canada", query: "gros morne newfoundland canada" },
  { name: "Torngat Mountains, Canada", query: "torngat mountains canada" },
  { name: "Tulum, Mexico", query: "tulum mexico ruins turquoise sea" },
  { name: "Sumidero Canyon, Mexico", query: "sumidero canyon chiapas mexico" },
  { name: "Hierve el Agua, Mexico", query: "hierve el agua oaxaca mexico" },
  { name: "Lake Atitl\u00e1n, Guatemala", query: "lake atitlan guatemala volcano" },
  { name: "Semuc Champey, Guatemala", query: "semuc champey guatemala pools" },
  { name: "Great Blue Hole, Belize", query: "great blue hole belize aerial" },
  { name: "Roat\u00e1n, Honduras", query: "roatan honduras reef beach" },
  { name: "Cerro Negro, Nicaragua", query: "cerro negro volcano nicaragua" },
  { name: "Monteverde, Costa Rica", query: "monteverde cloud forest costa rica" },
  { name: "Bocas del Toro, Panama", query: "bocas del toro panama islands" },
  { name: "Vi\u00f1ales, Cuba", query: "vinales cuba valley" },
  { name: "Saman\u00e1, Dominican Republic", query: "samana dominican republic coast" },
  { name: "El Yunque, Puerto Rico", query: "el yunque puerto rico rainforest" },
  { name: "Pitons, Saint Lucia", query: "pitons saint lucia" },
  { name: "The Baths, British Virgin Islands", query: "the baths virgin gorda" },
  // South America
  { name: "Torres del Paine, Chile", query: "torres del paine patagonia chile" },
  { name: "Machu Picchu, Peru", query: "machu picchu peru" },
  { name: "Iguazu Falls, Argentina", query: "iguazu falls argentina" },
  { name: "Salar de Uyuni, Bolivia", query: "salar de uyuni bolivia reflection" },
  { name: "Len\u00e7\u00f3is Maranhenses, Brazil", query: "lencois maranhenses brazil lagoons" },
  { name: "Rio de Janeiro, Brazil", query: "rio de janeiro brazil sugarloaf" },
  { name: "Chapada Diamantina, Brazil", query: "chapada diamantina brazil" },
  { name: "Fernando de Noronha, Brazil", query: "fernando de noronha brazil aerial" },
  { name: "Mount Roraima, Venezuela", query: "mount roraima venezuela" },
  { name: "Angel Falls, Venezuela", query: "angel falls venezuela" },
  { name: "Cocora Valley, Colombia", query: "cocora valley colombia wax palms" },
  { name: "Ca\u00f1o Cristales, Colombia", query: "cano cristales colombia river" },
  { name: "Gal\u00e1pagos, Ecuador", query: "galapagos ecuador landscape" },
  { name: "Cotopaxi, Ecuador", query: "cotopaxi ecuador volcano" },
  { name: "Huacachina, Peru", query: "huacachina peru oasis dunes" },
  { name: "Rainbow Mountain, Peru", query: "rainbow mountain peru" },
  { name: "Laguna Colorada, Bolivia", query: "laguna colorada bolivia flamingos" },
  { name: "Atacama Desert, Chile", query: "atacama desert chile night sky" },
  { name: "Marble Caves, Chile", query: "marble caves patagonia chile" },
  { name: "Perito Moreno, Argentina", query: "perito moreno glacier argentina" },
  { name: "Fitz Roy, Argentina", query: "fitz roy patagonia argentina" },
  { name: "Punta del Este, Uruguay", query: "punta del este uruguay coast" },
  { name: "Kaieteur Falls, Guyana", query: "kaieteur falls guyana" },
  { name: "Central Suriname Reserve, Suriname", query: "suriname rainforest river" },
  { name: "Los Roques, Venezuela", query: "los roques venezuela islands" },
  // Oceania and remote islands
  { name: "Milford Sound, New Zealand", query: "milford sound new zealand" },
  { name: "Aoraki, New Zealand", query: "aoraki mount cook new zealand" },
  { name: "Lake Tekapo, New Zealand", query: "lake tekapo new zealand lupins" },
  { name: "Tongariro, New Zealand", query: "tongariro alpine crossing new zealand" },
  { name: "Roy's Peak, New Zealand", query: "roys peak wanaka new zealand" },
  { name: "Cathedral Cove, New Zealand", query: "cathedral cove new zealand" },
  { name: "Great Barrier Reef, Australia", query: "great barrier reef australia aerial" },
  { name: "Uluru, Australia", query: "uluru australia sunset" },
  { name: "Twelve Apostles, Australia", query: "twelve apostles australia coast" },
  { name: "Whitehaven Beach, Australia", query: "whitehaven beach australia aerial" },
  { name: "Cradle Mountain, Australia", query: "cradle mountain tasmania australia" },
  { name: "Kakadu, Australia", query: "kakadu australia wetlands" },
  { name: "Bora Bora, French Polynesia", query: "bora bora french polynesia aerial" },
  { name: "Moorea, French Polynesia", query: "moorea french polynesia mountains" },
  { name: "Aitutaki, Cook Islands", query: "aitutaki cook islands lagoon" },
  { name: "Yasawa Islands, Fiji", query: "yasawa islands fiji" },
  { name: "Savai'i, Samoa", query: "savaii samoa waterfall coast" },
  { name: "Vava\u02bbu, Tonga", query: "vavau tonga islands" },
  { name: "Espiritu Santo, Vanuatu", query: "espiritu santo vanuatu blue hole" },
  { name: "Rock Islands, Palau", query: "rock islands palau aerial" },
  { name: "Kokoda Track, Papua New Guinea", query: "kokoda track papua new guinea mountains" },
  { name: "Easter Island, Chile", query: "easter island chile moai" },
  { name: "Lord Howe Island, Australia", query: "lord howe island australia" },
  { name: "Norfolk Island, Australia", query: "norfolk island australia coast" },
];
