/**
 * The in-app changelog shown by the What's New dialog after an update.
 *
 * Entries are generated by scripts/fork/generate-changelog.mjs during native
 * Mac/Windows packaging: one entry per shipped fork build, newest first,
 * covering both T3 Pretty's own changes and the integrated parent T3 Code
 * nightly. Versions match the fork release version baked into the build.
 * Keep entries user-facing: what someone using the app would notice, not
 * internal refactors. Dates are ISO (YYYY-MM-DD).
 */

export type ChangelogItemKind = "new" | "improved" | "fixed";

export interface ChangelogItem {
  readonly kind: ChangelogItemKind;
  readonly title: string;
  readonly description?: string;
}

export interface ChangelogRelease {
  readonly version: string;
  readonly date: string;
  readonly headline?: string;
  readonly items: readonly ChangelogItem[];
}

export const CHANGELOG_RELEASES: readonly ChangelogRelease[] = [
  {
    version: "0.0.34-nightly.20260823.1170000814",
    date: "2026-08-23",
    items: [
      {
        kind: "fixed",
        title: "remember pull request list filters",
      },
      {
        kind: "fixed",
        title: "align composer task drawer hover chrome",
      },
      {
        kind: "fixed",
        title: "warm thread state across machine handoffs",
      },
      {
        kind: "fixed",
        title: "sync thread animations with web",
      },
      {
        kind: "new",
        title: "rework model picker into one instant-apply panel",
      },
      {
        kind: "new",
        title: "show live thread details in activities",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260823.1166000811",
    date: "2026-08-23",
    items: [
      {
        kind: "fixed",
        title: "remember pull request list filters",
      },
      {
        kind: "fixed",
        title: "align composer task drawer hover chrome",
      },
      {
        kind: "fixed",
        title: "warm thread state across machine handoffs",
      },
      {
        kind: "fixed",
        title: "sync thread animations with web",
      },
      {
        kind: "new",
        title: "rework model picker into one instant-apply panel",
      },
      {
        kind: "new",
        title: "show live thread details in activities",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260823.1166000802",
    date: "2026-08-23",
    items: [
      {
        kind: "fixed",
        title: "warm thread state across machine handoffs",
      },
      {
        kind: "fixed",
        title: "sync thread animations with web",
      },
      {
        kind: "new",
        title: "rework model picker into one instant-apply panel",
      },
      {
        kind: "new",
        title: "show live thread details in activities",
      },
      {
        kind: "fixed",
        title: "smooth thread loading, switching, and streaming animations",
      },
      {
        kind: "new",
        title: "rewrite the live activity line with generated headlines",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260823.1166000761",
    date: "2026-08-23",
    items: [
      {
        kind: "fixed",
        title: "warm thread state across machine handoffs",
      },
      {
        kind: "fixed",
        title: "sync thread animations with web",
      },
      {
        kind: "new",
        title: "rework model picker into one instant-apply panel",
      },
      {
        kind: "new",
        title: "show live thread details in activities",
      },
      {
        kind: "fixed",
        title: "smooth thread loading, switching, and streaming animations",
      },
      {
        kind: "new",
        title: "rewrite the live activity line with generated headlines",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260823.1166000754",
    date: "2026-08-23",
    items: [
      {
        kind: "fixed",
        title: "sync thread animations with web",
      },
      {
        kind: "new",
        title: "rework model picker into one instant-apply panel",
      },
      {
        kind: "new",
        title: "show live thread details in activities",
      },
      {
        kind: "fixed",
        title: "smooth thread loading, switching, and streaming animations",
      },
      {
        kind: "new",
        title: "rewrite the live activity line with generated headlines",
      },
      {
        kind: "new",
        title: "redesign PR page with frosted glass scenery and submenu filters",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260823.1166000749",
    date: "2026-08-23",
    items: [
      {
        kind: "new",
        title: "rework model picker into one instant-apply panel",
      },
      {
        kind: "new",
        title: "show live thread details in activities",
      },
      {
        kind: "fixed",
        title: "smooth thread loading, switching, and streaming animations",
      },
      {
        kind: "new",
        title: "rewrite the live activity line with generated headlines",
      },
      {
        kind: "new",
        title: "redesign PR page with frosted glass scenery and submenu filters",
      },
      {
        kind: "new",
        title: "pick and manage skills in the new-task view",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260823.1166000741",
    date: "2026-08-23",
    items: [
      {
        kind: "new",
        title: "show live thread details in activities",
      },
      {
        kind: "fixed",
        title: "smooth thread loading, switching, and streaming animations",
      },
      {
        kind: "new",
        title: "rewrite the live activity line with generated headlines",
      },
      {
        kind: "new",
        title: "redesign PR page with frosted glass scenery and submenu filters",
      },
      {
        kind: "new",
        title: "pick and manage skills in the new-task view",
      },
      {
        kind: "fixed",
        title: "stop PR row metadata overlapping the diff stat in narrow lists",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260823.1164000734",
    date: "2026-08-23",
    items: [
      {
        kind: "new",
        title: "show live thread details in activities",
      },
      {
        kind: "fixed",
        title: "smooth thread loading, switching, and streaming animations",
      },
      {
        kind: "new",
        title: "rewrite the live activity line with generated headlines",
      },
      {
        kind: "new",
        title: "redesign PR page with frosted glass scenery and submenu filters",
      },
      {
        kind: "new",
        title: "pick and manage skills in the new-task view",
      },
      {
        kind: "fixed",
        title: "stop PR row metadata overlapping the diff stat in narrow lists",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260823.1164000729",
    date: "2026-08-23",
    items: [
      {
        kind: "fixed",
        title: "smooth thread loading, switching, and streaming animations",
      },
      {
        kind: "new",
        title: "rewrite the live activity line with generated headlines",
      },
      {
        kind: "new",
        title: "redesign PR page with frosted glass scenery and submenu filters",
      },
      {
        kind: "new",
        title: "pick and manage skills in the new-task view",
      },
      {
        kind: "fixed",
        title: "stop PR row metadata overlapping the diff stat in narrow lists",
      },
      {
        kind: "fixed",
        title: "load pull requests whose recorded repository predates a remote change",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260823.1164000722",
    date: "2026-08-23",
    items: [
      {
        kind: "new",
        title: "rewrite the live activity line with generated headlines",
      },
      {
        kind: "new",
        title: "redesign PR page with frosted glass scenery and submenu filters",
      },
      {
        kind: "new",
        title: "pick and manage skills in the new-task view",
      },
      {
        kind: "fixed",
        title: "stop PR row metadata overlapping the diff stat in narrow lists",
      },
      {
        kind: "fixed",
        title: "load pull requests whose recorded repository predates a remote change",
      },
      {
        kind: "fixed",
        title: "prevent loading fallback timer from resetting",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260823.1164000704",
    date: "2026-08-23",
    items: [
      {
        kind: "new",
        title: "redesign PR page with frosted glass scenery and submenu filters",
      },
      {
        kind: "new",
        title: "pick and manage skills in the new-task view",
      },
      {
        kind: "fixed",
        title: "stop PR row metadata overlapping the diff stat in narrow lists",
      },
      {
        kind: "fixed",
        title: "load pull requests whose recorded repository predates a remote change",
      },
      {
        kind: "fixed",
        title: "prevent loading fallback timer from resetting",
      },
      {
        kind: "new",
        title: "standard queue/steer controls for messages sent while the agent is running",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260823.1164000691",
    date: "2026-08-23",
    items: [
      {
        kind: "new",
        title: "pick and manage skills in the new-task view",
      },
      {
        kind: "fixed",
        title: "stop PR row metadata overlapping the diff stat in narrow lists",
      },
      {
        kind: "fixed",
        title: "load pull requests whose recorded repository predates a remote change",
      },
      {
        kind: "fixed",
        title: "prevent loading fallback timer from resetting",
      },
      {
        kind: "new",
        title: "standard queue/steer controls for messages sent while the agent is running",
      },
      {
        kind: "fixed",
        title: "removing a Surge Connect environment now deletes it for good",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260823.1164000677",
    date: "2026-08-23",
    items: [
      {
        kind: "fixed",
        title: "load pull requests whose recorded repository predates a remote change",
      },
      {
        kind: "fixed",
        title: "prevent loading fallback timer from resetting",
      },
      {
        kind: "new",
        title: "standard queue/steer controls for messages sent while the agent is running",
      },
      {
        kind: "fixed",
        title: "removing a Surge Connect environment now deletes it for good",
      },
      {
        kind: "fixed",
        title: "remove duplicate thinking indicator in the thread",
      },
      {
        kind: "fixed",
        title: "prevent markdown link parsing crash",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260823.1164000669",
    date: "2026-08-23",
    items: [
      {
        kind: "fixed",
        title: "prevent loading fallback timer from resetting",
      },
      {
        kind: "new",
        title: "standard queue/steer controls for messages sent while the agent is running",
      },
      {
        kind: "fixed",
        title: "removing a Surge Connect environment now deletes it for good",
      },
      {
        kind: "fixed",
        title: "remove duplicate thinking indicator in the thread",
      },
      {
        kind: "fixed",
        title: "prevent markdown link parsing crash",
      },
      {
        kind: "new",
        title: "expand world photos and add four photo themes",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260823.1164000666",
    date: "2026-08-23",
    items: [
      {
        kind: "new",
        title: "standard queue/steer controls for messages sent while the agent is running",
      },
      {
        kind: "fixed",
        title: "removing a Surge Connect environment now deletes it for good",
      },
      {
        kind: "fixed",
        title: "remove duplicate thinking indicator in the thread",
      },
      {
        kind: "fixed",
        title: "prevent markdown link parsing crash",
      },
      {
        kind: "new",
        title: "expand world photos and add four photo themes",
      },
      {
        kind: "new",
        title: "ship a headless T3 Pretty CLI for Surge Connect",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260823.1164000664",
    date: "2026-08-23",
    items: [
      {
        kind: "new",
        title: "standard queue/steer controls for messages sent while the agent is running",
      },
      {
        kind: "fixed",
        title: "removing a Surge Connect environment now deletes it for good",
      },
      {
        kind: "fixed",
        title: "remove duplicate thinking indicator in the thread",
      },
      {
        kind: "fixed",
        title: "prevent markdown link parsing crash",
      },
      {
        kind: "new",
        title: "expand world photos and add four photo themes",
      },
      {
        kind: "new",
        title: "ship a headless T3 Pretty CLI for Surge Connect",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260823.1164000661",
    date: "2026-08-23",
    items: [
      {
        kind: "fixed",
        title: "removing a Surge Connect environment now deletes it for good",
      },
      {
        kind: "fixed",
        title: "remove duplicate thinking indicator in the thread",
      },
      {
        kind: "fixed",
        title: "prevent markdown link parsing crash",
      },
      {
        kind: "new",
        title: "expand world photos and add four photo themes",
      },
      {
        kind: "new",
        title: "ship a headless T3 Pretty CLI for Surge Connect",
      },
      {
        kind: "fixed",
        title: 'standardize reasoning effort labels to "<level> effort"',
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260822.1162000644",
    date: "2026-08-23",
    items: [
      {
        kind: "fixed",
        title: "removing a Surge Connect environment now deletes it for good",
      },
      {
        kind: "fixed",
        title: "remove duplicate thinking indicator in the thread",
      },
      {
        kind: "fixed",
        title: "prevent markdown link parsing crash",
      },
      {
        kind: "new",
        title: "expand world photos and add four photo themes",
      },
      {
        kind: "new",
        title: "ship a headless T3 Pretty CLI for Surge Connect",
      },
      {
        kind: "fixed",
        title: 'standardize reasoning effort labels to "<level> effort"',
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260822.1162000641",
    date: "2026-08-23",
    items: [
      {
        kind: "fixed",
        title: "remove duplicate thinking indicator in the thread",
      },
      {
        kind: "fixed",
        title: "prevent markdown link parsing crash",
      },
      {
        kind: "new",
        title: "expand world photos and add four photo themes",
      },
      {
        kind: "new",
        title: "ship a headless T3 Pretty CLI for Surge Connect",
      },
      {
        kind: "fixed",
        title: 'standardize reasoning effort labels to "<level> effort"',
      },
      {
        kind: "fixed",
        title: "globally enabled skills can still be favorited",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260822.1162000626",
    date: "2026-08-22",
    items: [
      {
        kind: "fixed",
        title: "prevent markdown link parsing crash",
      },
      {
        kind: "new",
        title: "expand world photos and add four photo themes",
      },
      {
        kind: "new",
        title: "ship a headless T3 Pretty CLI for Surge Connect",
      },
      {
        kind: "fixed",
        title: 'standardize reasoning effort labels to "<level> effort"',
      },
      {
        kind: "fixed",
        title: "globally enabled skills can still be favorited",
      },
      {
        kind: "fixed",
        title: "auto-dismiss in-app toasts after 5–10s",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260822.1162000621",
    date: "2026-08-22",
    items: [
      {
        kind: "new",
        title: "expand world photos and add four photo themes",
      },
      {
        kind: "new",
        title: "ship a headless T3 Pretty CLI for Surge Connect",
      },
      {
        kind: "fixed",
        title: 'standardize reasoning effort labels to "<level> effort"',
      },
      {
        kind: "fixed",
        title: "globally enabled skills can still be favorited",
      },
      {
        kind: "fixed",
        title: "auto-dismiss in-app toasts after 5–10s",
      },
      {
        kind: "fixed",
        title: "keep thread Copy flyout clickable and copy conversation",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260822.1155000616",
    date: "2026-08-22",
    items: [
      {
        kind: "new",
        title: "expand world photos and add four photo themes",
      },
      {
        kind: "new",
        title: "ship a headless T3 Pretty CLI for Surge Connect",
      },
      {
        kind: "fixed",
        title: 'standardize reasoning effort labels to "<level> effort"',
      },
      {
        kind: "fixed",
        title: "globally enabled skills can still be favorited",
      },
      {
        kind: "fixed",
        title: "auto-dismiss in-app toasts after 5–10s",
      },
      {
        kind: "fixed",
        title: "keep thread Copy flyout clickable and copy conversation",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260822.1155000602",
    date: "2026-08-22",
    items: [
      {
        kind: "new",
        title: "expand world photos and add four photo themes",
      },
      {
        kind: "new",
        title: "ship a headless T3 Pretty CLI for Surge Connect",
      },
      {
        kind: "fixed",
        title: 'standardize reasoning effort labels to "<level> effort"',
      },
      {
        kind: "fixed",
        title: "globally enabled skills can still be favorited",
      },
      {
        kind: "fixed",
        title: "auto-dismiss in-app toasts after 5–10s",
      },
      {
        kind: "fixed",
        title: "keep thread Copy flyout clickable and copy conversation",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260822.1155000599",
    date: "2026-08-22",
    items: [
      {
        kind: "new",
        title: "ship a headless T3 Pretty CLI for Surge Connect",
      },
      {
        kind: "fixed",
        title: 'standardize reasoning effort labels to "<level> effort"',
      },
      {
        kind: "fixed",
        title: "globally enabled skills can still be favorited",
      },
      {
        kind: "fixed",
        title: "auto-dismiss in-app toasts after 5–10s",
      },
      {
        kind: "fixed",
        title: "keep thread Copy flyout clickable and copy conversation",
      },
      {
        kind: "fixed",
        title: "restore in-app What's New notes after Aug 12",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260822.1155000594",
    date: "2026-08-22",
    items: [
      {
        kind: "new",
        title: "ship a headless T3 Pretty CLI for Surge Connect",
      },
      {
        kind: "fixed",
        title: 'standardize reasoning effort labels to "<level> effort"',
      },
      {
        kind: "fixed",
        title: "globally enabled skills can still be favorited",
      },
      {
        kind: "fixed",
        title: "auto-dismiss in-app toasts after 5–10s",
      },
      {
        kind: "fixed",
        title: "keep thread Copy flyout clickable and copy conversation",
      },
      {
        kind: "fixed",
        title: "restore in-app What's New notes after Aug 12",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260817.1120367814",
    date: "2026-08-18",
    items: [
      {
        kind: "fixed",
        title: "show all usage breakdown periods (#7219)",
      },
      {
        kind: "fixed",
        title: "rotate snoozed and settled shelf chevrons (#7276)",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260817.1119881461",
    date: "2026-08-18",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260817.1119509998",
    date: "2026-08-18",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260817.1119470579",
    date: "2026-08-18",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260817.1119043470",
    date: "2026-08-18",
    items: [
      {
        kind: "new",
        title: "make review verdicts legible in the pull request detail (#7077)",
      },
      {
        kind: "fixed",
        title: "clamp model picker to available height above anchor",
      },
      {
        kind: "new",
        title: "redesign pull request menu and conversation",
      },
      {
        kind: "new",
        title: "start new threads immediately and show thinking",
      },
      {
        kind: "new",
        title: "keep model options above long catalogs",
      },
      {
        kind: "fixed",
        title: "make the iOS Live Activity glanceable",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260817.1116000227",
    date: "2026-08-17",
    items: [
      {
        kind: "fixed",
        title: "pin iOS threads to the true bottom on open",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260817.1116000226",
    date: "2026-08-17",
    items: [
      {
        kind: "new",
        title: "let users withhold browser access from agents (#7083)",
      },
      {
        kind: "fixed",
        title: "center the context usage meter (#7296)",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260817.1113000225",
    date: "2026-08-16",
    items: [
      {
        kind: "fixed",
        title: "use latest canvas doc after context menu",
      },
      {
        kind: "fixed",
        title: "make canvas right-click delete and rename work",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260817.1113000224",
    date: "2026-08-16",
    items: [
      {
        kind: "fixed",
        title: "restore desktop update install confirmation",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260817.1113000223",
    date: "2026-08-16",
    items: [
      {
        kind: "fixed",
        title: "restore nightly auto-update downloads from the GitHub generic feed",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260817.1113000222",
    date: "2026-08-16",
    items: [
      {
        kind: "fixed",
        title: "capture Windows crashes reliably",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260817.1113000221",
    date: "2026-08-16",
    items: [
      {
        kind: "new",
        title: "add search and favorites to the skills picker",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260817.1113000220",
    date: "2026-08-16",
    items: [
      {
        kind: "fixed",
        title: "start new-thread fog earlier and clear it more smoothly",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260817.1113000219",
    date: "2026-08-16",
    items: [
      {
        kind: "new",
        title: "start threads from the canvas",
      },
      {
        kind: "fixed",
        title: "stop Windows from quitting after GPU process deaths",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260817.1113000217",
    date: "2026-08-17",
    items: [
      {
        kind: "new",
        title: "configurable browser defaults in Settings → Integrations (#7082)",
      },
      {
        kind: "fixed",
        title: "protect provider API budgets (#6466)",
      },
      {
        kind: "new",
        title: "ban native title tooltips and migrate to styled Tooltip (#7209)",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260816.1110000216",
    date: "2026-08-16",
    items: [
      {
        kind: "fixed",
        title: "do not pretty-break case-pattern pipes",
      },
      {
        kind: "fixed",
        title: "keep bash pretty-break from rewriting comments and ${}",
      },
      {
        kind: "fixed",
        title: "format and highlight agent bash commands",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260816.1110000215",
    date: "2026-08-16",
    items: [
      {
        kind: "fixed",
        title: "hide World Scenery credit when scrolled up",
      },
      {
        kind: "new",
        title: "cloud-bank fog, cross-route composer glide, softer live motion",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260816.1110000213",
    date: "2026-08-16",
    items: [
      {
        kind: "fixed",
        title: "dock World Scenery credits to the hero footer",
      },
      {
        kind: "fixed",
        title: "let the right panel slide open after its content mounts",
      },
      {
        kind: "fixed",
        title: "move World Scenery credits below the chat box",
      },
      {
        kind: "improved",
        title: "consolidate composer footer into overflow menu",
      },
      {
        kind: "fixed",
        title: "keep new-thread fog smooth until the photo is ready",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260816.1110000209",
    date: "2026-08-16",
    items: [
      {
        kind: "fixed",
        title: "resolve host skills by id and keep them on discovery failure",
      },
      {
        kind: "fixed",
        title: "lock host skills by selected instance, not driver",
      },
      {
        kind: "new",
        title: "fuller slash and @ menus, all skills in the composer picker",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260816.1110000208",
    date: "2026-08-16",
    items: [
      {
        kind: "fixed",
        title: "price Kimi Code models at official API rates",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260816.1110000207",
    date: "2026-08-16",
    items: [
      {
        kind: "fixed",
        title: "lift World Scenery dark selected chips",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260816.1110000206",
    date: "2026-08-16",
    items: [
      {
        kind: "fixed",
        title: "retry dormant preview readiness",
      },
      {
        kind: "improved",
        title: "implement Phase 3 desktop and preview efficiency cuts",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260816.1110000204",
    date: "2026-08-16",
    items: [
      {
        kind: "new",
        title: "add global and per-thread subagent policy",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260816.1110000203",
    date: "2026-08-16",
    items: [
      {
        kind: "improved",
        title: "implement Phase 2 structural efficiency cuts",
      },
      {
        kind: "fixed",
        title: "cancel storage walks and keep scan totals stable",
      },
      {
        kind: "fixed",
        title: "address storage scan review comments",
      },
      {
        kind: "fixed",
        title: "bound portable directory size stat concurrency",
      },
      {
        kind: "fixed",
        title: "stream storage scan progress at the top",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260816.1110000201",
    date: "2026-08-16",
    items: [
      {
        kind: "fixed",
        title: "keep colliding folders and picker state stable",
      },
      {
        kind: "fixed",
        title: "skill toggles no longer race the server, mentions survive odd names",
      },
      {
        kind: "fixed",
        title: "tighten skill dedupe, sharing, and marketplace edge cases",
      },
      {
        kind: "fixed",
        title: "keep AnchoredMenu at upstream's AndroidAnchoredMenu path",
      },
      {
        kind: "fixed",
        title: "implement-plan threads inherit the plan thread's skills",
      },
      {
        kind: "fixed",
        title: "send enabled skills' instructions with the turn",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260816.1106000185",
    date: "2026-08-16",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260816.1105000184",
    date: "2026-08-15",
    items: [
      {
        kind: "fixed",
        title: "let Windows desktop reach Surge remotes",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260816.1105000183",
    date: "2026-08-16",
    items: [
      {
        kind: "fixed",
        title: "keep highlighted command menu items clear of the scroll fade (#7132)",
      },
      {
        kind: "improved",
        title: "simplify advanced theme controls (#7107)",
      },
      {
        kind: "fixed",
        title: "restore dark theme palette (#6663)",
      },
      {
        kind: "new",
        title: "send PR line requests to agent (#6597)",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260815.1102000182",
    date: "2026-08-15",
    items: [
      {
        kind: "fixed",
        title: "submit TestFlight on every release",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260815.1102000180",
    date: "2026-08-15",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260815.1102000179",
    date: "2026-08-15",
    items: [
      {
        kind: "new",
        title: "toggle provider CLI skills",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260815.1102000177",
    date: "2026-08-15",
    items: [
      {
        kind: "new",
        title: "add environment storage settings for managed worktrees",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260815.1102000176",
    date: "2026-08-15",
    items: [
      {
        kind: "fixed",
        title: "keep an open pull request current",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260815.1102000175",
    date: "2026-08-15",
    items: [
      {
        kind: "fixed",
        title: "refresh skills list after uninstall",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260815.1102000174",
    date: "2026-08-15",
    items: [
      {
        kind: "fixed",
        title: "stop canvas captures from crashing the panel",
      },
      {
        kind: "new",
        title: "show skill loads in the thread log",
      },
      {
        kind: "new",
        title: "add signal macOS DMG installer background (#6201)",
      },
      {
        kind: "fixed",
        title: "keep timestamp date and time in the same locale (#7081)",
      },
      {
        kind: "fixed",
        title: "default clone destination to folder plus repo name (#5989)",
      },
      {
        kind: "fixed",
        title: "restore CLAUDE.md symlink target (#3929)",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260815.1101000169",
    date: "2026-08-15",
    items: [
      {
        kind: "fixed",
        title: "type optional grok reasoning effort as undefined",
      },
      {
        kind: "fixed",
        title: "advertise grok reasoning effort by model",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260815.1101000168",
    date: "2026-08-15",
    items: [
      {
        kind: "new",
        title: "manage provider CLI skills on each environment",
      },
      {
        kind: "fixed",
        title: "preserve XML-like tags in user messages (#4133)",
      },
      {
        kind: "fixed",
        title: "scale command details with code font (#6510)",
      },
      {
        kind: "fixed",
        title: "show selected model in context window tooltip (#4772)",
      },
      {
        kind: "fixed",
        title: "retain terminal PR badges after checkout switch (#4755)",
      },
      {
        kind: "fixed",
        title: "let slow provider CLIs raise their discovery probe budget (#6223)",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260815.1098000165",
    date: "2026-08-15",
    items: [
      {
        kind: "fixed",
        title: "include enabledSkillIds when bootstrapping threads",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260815.1098000164",
    date: "2026-08-15",
    items: [
      {
        kind: "fixed",
        title: "align pull request action menu rows (#6534)",
      },
      {
        kind: "new",
        title: "older chat timestamps show the date, not just the time (#6654)",
      },
      {
        kind: "improved",
        title: "refresh workspace layouts and tool activity (#6657)",
      },
      {
        kind: "new",
        title: "refresh workspace layouts and tool activity",
      },
      {
        kind: "new",
        title: "open remote environments in your local editor over SSH (#6572)",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260815.1097000163",
    date: "2026-08-15",
    items: [
      {
        kind: "fixed",
        title: "bound OKLCH gamut mapping (#6485)",
      },
      {
        kind: "new",
        title: "maintain AUR packages in-repo (#4128)",
      },
      {
        kind: "fixed",
        title: "handle files named HEAD in git status (#6397)",
      },
      {
        kind: "improved",
        title: "simplify global styling (#6381)",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260814.1096000162",
    date: "2026-08-14",
    items: [
      {
        kind: "fixed",
        title: "repair cross-file seams from the upstream nightly merge",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260814.1096000161",
    date: "2026-08-14",
    items: [
      {
        kind: "fixed",
        title: "style sidebar action tooltips (#6371)",
      },
      {
        kind: "improved",
        title: "speed up Windows update installation (#6169)",
      },
      {
        kind: "fixed",
        title: "add copying terminal selection with ctrl+c in the web app (#5638)",
      },
      {
        kind: "fixed",
        title: "terminal subprocess polling no longer floods the PID space (#6377)",
      },
      {
        kind: "fixed",
        title: "clarify desktop update status (#6504)",
      },
      {
        kind: "fixed",
        title: "steer active turns by default (#6543)",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260813.1087000158",
    date: "2026-08-14",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260813.1087000157",
    date: "2026-08-14",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260813.1087000156",
    date: "2026-08-14",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260813.1087000155",
    date: "2026-08-14",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260813.1087000154",
    date: "2026-08-14",
    items: [
      {
        kind: "fixed",
        title: "add enabledSkillIds to snapshot-cache fixtures",
      },
      {
        kind: "improved",
        title: "trim terminal buffers incrementally and plug small UI leaks",
      },
      {
        kind: "improved",
        title: "stop pinning every environment shell for the app lifetime",
      },
      {
        kind: "improved",
        title: "probe before foreground reconnects and gate refetch storms",
      },
      {
        kind: "improved",
        title: "bound image, draft, review, and thread-cache growth",
      },
      {
        kind: "improved",
        title: "make feed derivation incremental and row identities stable",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260813.1087000152",
    date: "2026-08-14",
    items: [
      {
        kind: "fixed",
        title: "add enabledSkillIds to thread shell fixtures",
      },
      {
        kind: "new",
        title: "skills settings page and composer skills picker",
      },
      {
        kind: "new",
        title: "skills atoms and thread skill commands",
      },
      {
        kind: "new",
        title: "skills registry, marketplace, and per-turn workspace materialization",
      },
      {
        kind: "new",
        title: "skills registry, marketplace, and per-thread skill contracts",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260813.1087000151",
    date: "2026-08-14",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260813.1087000150",
    date: "2026-08-13",
    items: [
      {
        kind: "new",
        title: "resolve review conversations from the pull request summary tab",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260813.1087000149",
    date: "2026-08-13",
    items: [
      {
        kind: "fixed",
        title: "restart outgoing scenery fades and keep them out of ink snapshots",
      },
      {
        kind: "fixed",
        title: "keep scenery swap fades valid and fall back without view transitions",
      },
      {
        kind: "fixed",
        title: "dissolve outgoing scenery photo on thread switch",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260813.1087000148",
    date: "2026-08-13",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260813.1087000147",
    date: "2026-08-13",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260813.1087000146",
    date: "2026-08-13",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260813.1087000145",
    date: "2026-08-13",
    items: [
      {
        kind: "fixed",
        title: "skip usage scans for disconnected environments",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260813.1087000144",
    date: "2026-08-13",
    items: [
      {
        kind: "improved",
        title: "slim the per-event orchestration write path",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260813.1087000143",
    date: "2026-08-13",
    items: [
      {
        kind: "fixed",
        title: "preserve sidebar preference on clamped drag frames",
      },
      {
        kind: "fixed",
        title: "keep sidebar resizable when the window changes without a resize event",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260813.1087000142",
    date: "2026-08-13",
    items: [
      {
        kind: "fixed",
        title: "buffer the nested ExpoModulesJSI build output",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260813.1087000141",
    date: "2026-08-13",
    items: [
      {
        kind: "fixed",
        title: "hide sidebar stage pill before it overflows the header",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260813.1087000140",
    date: "2026-08-13",
    items: [
      {
        kind: "fixed",
        title: "normalize Yolo to Full access when switching providers",
      },
      {
        kind: "new",
        title: "replace Full access with Auto and Yolo modes",
      },
      {
        kind: "fixed",
        title: "extend blockquotes across wrapped lines (#6482)",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260813.1086000138",
    date: "2026-08-13",
    items: [
      {
        kind: "fixed",
        title: "build the widget appex from its own Info.plist",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260813.1086000137",
    date: "2026-08-13",
    items: [
      {
        kind: "fixed",
        title: "keep Android link alerts within three buttons",
      },
      {
        kind: "fixed",
        title: "show images after sending a new thread",
      },
      {
        kind: "fixed",
        title: "show copy and open actions when long-pressing chat links",
      },
      {
        kind: "fixed",
        title: "fit the iOS thread header and clear stuck loading overlay",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260813.1086000134",
    date: "2026-08-13",
    items: [
      {
        kind: "fixed",
        title: "hide scenery credits and move the model picker below chat",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260813.1086000133",
    date: "2026-08-13",
    items: [
      {
        kind: "fixed",
        title: "keep the widget version script out of the pbxproj",
      },
      {
        kind: "fixed",
        title: "ignore pull request actions in latency tracker (#6476)",
      },
      {
        kind: "fixed",
        title: "keep pull request panel within viewport (#6451)",
      },
      {
        kind: "fixed",
        title: "keep turn minimap stable as composer grows (#6414)",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260813.1084000130",
    date: "2026-08-13",
    items: [
      {
        kind: "fixed",
        title: "copy app CFBundleVersion onto the widget at archive time",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260813.1084000129",
    date: "2026-08-13",
    items: [
      {
        kind: "fixed",
        title: "align Codex collaboration prompts (#6432)",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260813.1082000128",
    date: "2026-08-13",
    items: [
      {
        kind: "fixed",
        title: "sync widget CFBundleVersion with the app",
      },
      {
        kind: "fixed",
        title: "remove thinking orbs and restore pulse-dot status",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260813.1082000126",
    date: "2026-08-13",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260813.1082000124",
    date: "2026-08-13",
    items: [
      {
        kind: "fixed",
        title: "let local EAS npx parse nitro-markdown overrides",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260813.1082000123",
    date: "2026-08-13",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260813.1082000122",
    date: "2026-08-12",
    items: [
      {
        kind: "fixed",
        title: "persist local iOS submit fingerprints",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260813.1082000121",
    date: "2026-08-13",
    items: [
      {
        kind: "fixed",
        title: "keep diff file lists scrollable past expanded files (#6423)",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260813.1081000120",
    date: "2026-08-12",
    items: [
      {
        kind: "fixed",
        title: "keep the typed prompt when a draft changes repo (#6393)",
      },
      {
        kind: "fixed",
        title: "make reset zoom hover visible (#6385)",
      },
      {
        kind: "new",
        title: "project favicon and workspace icons in command subtitles (#6330)",
      },
      {
        kind: "fixed",
        title: "cmd+click sidebar PR numbers open in the browser (#6378)",
      },
      {
        kind: "new",
        title:
          "pull request surfaces — filters & qualifiers, all-server listing, update branch, reactions, in-place editing, smarter diffs (#6039)",
      },
      {
        kind: "new",
        title: "deregister account environments from any client (#4844)",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260812.1077000119",
    date: "2026-08-12",
    items: [
      {
        kind: "fixed",
        title: "prepare PR checkout from new-task handoff",
      },
      {
        kind: "fixed",
        title: "detect pull requests created at the end of a turn",
      },
      {
        kind: "new",
        title: "show model details in the chat view",
      },
      {
        kind: "fixed",
        title: "open PR fix in new-task sheet",
      },
      {
        kind: "fixed",
        title: "open thread PR links in the native pull request view",
      },
      {
        kind: "fixed",
        title: "keep pull request chrome below the iOS nav bar",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260812.1077000112",
    date: "2026-08-12",
    items: [
      {
        kind: "fixed",
        title: "virtualize diffs and expand withheld add/rename files",
      },
      {
        kind: "fixed",
        title: "load withheld diffs and recover list continuations",
      },
      {
        kind: "fixed",
        title: "honor host capabilities in the native pull-request workspace",
      },
      {
        kind: "fixed",
        title: "address native pull-request review findings",
      },
      {
        kind: "new",
        title: "add a native pull-request manager",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260812.1077000111",
    date: "2026-08-12",
    items: [
      {
        kind: "improved",
        title: "reduce desktop and mobile hot-path work",
      },
      {
        kind: "fixed",
        title: "repair LegendList patch metadata",
      },
      {
        kind: "fixed",
        title: "close scenery settings when the right panel opens",
      },
      {
        kind: "improved",
        title: "reduce long-session overhead",
      },
      {
        kind: "fixed",
        title: "keep Unsplash credits visible with the right panel open",
      },
      {
        kind: "fixed",
        title: "hide World Scenery credits when the right panel is open",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260812.1077000102",
    date: "2026-08-12",
    items: [
      {
        kind: "fixed",
        title: "give snoozed and settled shelves the inbox card language",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260812.1077000101",
    date: "2026-08-12",
    items: [
      {
        kind: "fixed",
        title: "dissolve World Scenery ink when threads flip light and dark",
      },
      {
        kind: "improved",
        title: "cut focused thinking-orb CPU",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260812.1077000099",
    date: "2026-08-12",
    items: [
      {
        kind: "new",
        title: "expose Auto Cost/Balance/Intelligence modes",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260812.1077000098",
    date: "2026-08-12",
    items: [
      {
        kind: "fixed",
        title: "center scenery credits under the bottom bar",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260812.1077000097",
    date: "2026-08-12",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260812.1077000096",
    date: "2026-08-12",
    items: [
      {
        kind: "new",
        title: "reset sidebar width on double click (#6320)",
      },
      {
        kind: "fixed",
        title: "theme Clerk surfaces (#6300)",
      },
      {
        kind: "fixed",
        title: "prevent changed files header overlap (#6314)",
      },
      {
        kind: "fixed",
        title: "preserve CLI OAuth parameters through browser sign-in (#6285)",
      },
      {
        kind: "fixed",
        title: "align mobile onboarding header (#6293)",
      },
      {
        kind: "new",
        title: "a better right panel empty state (#6258)",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1067000094",
    date: "2026-08-12",
    items: [
      {
        kind: "fixed",
        title: "make upstream retries reliable",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1067000093",
    date: "2026-08-12",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1067000092",
    date: "2026-08-11",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1067000090",
    date: "2026-08-11",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1067000089",
    date: "2026-08-11",
    items: [
      {
        kind: "improved",
        title: "retire EAS bootstrap helper [skip ci]",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1067000088",
    date: "2026-08-11",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1067000087",
    date: "2026-08-11",
    items: [
      {
        kind: "fixed",
        title: "target T3 Pretty App Store record [skip ci]",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1067000086",
    date: "2026-08-11",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1067000085",
    date: "2026-08-11",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1067000084",
    date: "2026-08-11",
    items: [
      {
        kind: "improved",
        title: "clarify EAS credential bootstrap",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1067000083",
    date: "2026-08-11",
    items: [
      {
        kind: "fixed",
        title: "align widget release version",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1067000082",
    date: "2026-08-11",
    items: [
      {
        kind: "fixed",
        title: "stabilize production startup",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1067000081",
    date: "2026-08-11",
    items: [
      {
        kind: "fixed",
        title: "allow interactive EAS credential bootstrap",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1067000080",
    date: "2026-08-11",
    items: [
      {
        kind: "improved",
        title: "bootstrap initial iOS credentials",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1067000079",
    date: "2026-08-11",
    items: [
      {
        kind: "improved",
        title: "automate fork EAS releases",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1067000078",
    date: "2026-08-11",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1067000077",
    date: "2026-08-11",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1067000076",
    date: "2026-08-11",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1067000075",
    date: "2026-08-11",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1067000074",
    date: "2026-08-11",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1067000073",
    date: "2026-08-11",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1067000072",
    date: "2026-08-11",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1067000070",
    date: "2026-08-11",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1067000069",
    date: "2026-08-11",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1067000065",
    date: "2026-08-11",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1067000064",
    date: "2026-08-11",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1067000063",
    date: "2026-08-11",
    items: [
      {
        kind: "fixed",
        title: "route self-hosted GitLab remotes (#6061)",
      },
      {
        kind: "fixed",
        title: "handle unborn HEAD in VCS status (#5944)",
      },
      {
        kind: "fixed",
        title: "advertise 256-color TERM on Windows terminals (#5693)",
      },
      {
        kind: "fixed",
        title: "skip Linux libc detection on Windows/macOS (#5354)",
      },
      {
        kind: "improved",
        title: "skip base64 for oversized image candidates (#5220)",
      },
      {
        kind: "fixed",
        title: "persist sidebar shelf collapse state (#5136)",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1063000060",
    date: "2026-08-10",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1063000059",
    date: "2026-08-10",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1063000058",
    date: "2026-08-10",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1063000057",
    date: "2026-08-10",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1063000056",
    date: "2026-08-10",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1063000055",
    date: "2026-08-10",
    items: [
      {
        kind: "fixed",
        title: "restore green checks after PR autosettle merges",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1063000054",
    date: "2026-08-10",
    items: [
      {
        kind: "new",
        title: "generate What's New changelog for every fork release (#45)",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260811.1063000053",
    date: "2026-08-11",
    items: [
      {
        kind: "new",
        title: "add three-hour snooze option (#5914)",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260810.1059000052",
    date: "2026-08-10",
    items: [
      {
        kind: "new",
        title:
          "T3 Pretty iOS app — rebrand, World Scenery default, Surge Connect, release train (#44)",
      },
      {
        kind: "fixed",
        title: "account for Windows window controls in PR page header (#6049)",
      },
      {
        kind: "fixed",
        title: "extend release publish timeout (#6034)",
      },
      {
        kind: "fixed",
        title: "improve built-in theme contrast (#6000)",
      },
      {
        kind: "new",
        title: "add duplicate action to the T3 Code default theme (#6013)",
      },
      {
        kind: "improved",
        title: "probe the Windows shell environment concurrently (#5878)",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260810.1059000051",
    date: "2026-08-10",
    items: [
      {
        kind: "fixed",
        title: "keep scenery credits dock off the chat box (#42)",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260810.1059000050",
    date: "2026-08-10",
    items: [
      {
        kind: "new",
        title: "add auto-PR toggle to chat composer (#43)",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260810.1059000049",
    date: "2026-08-10",
    items: [
      {
        kind: "new",
        title: "show What's New changelog dialog after updates (#41)",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260810.1059000048",
    date: "2026-08-10",
    items: [
      {
        kind: "fixed",
        title: "prefer origin over upstream for repository identity (#40)",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260810.1059000047",
    date: "2026-08-10",
    items: [
      {
        kind: "fixed",
        title: "migrate stale relay links",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260810.1059000046",
    date: "2026-08-10",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260810.1059000045",
    date: "2026-08-10",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260810.1059000043",
    date: "2026-08-10",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260810.1059000042",
    date: "2026-08-10",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.34-nightly.20260810.1059000041",
    date: "2026-08-10",
    items: [
      {
        kind: "improved",
        title: "prepare v0.0.33",
      },
      {
        kind: "fixed",
        title: "parse EAS fingerprint JSON (#5991)",
      },
      {
        kind: "fixed",
        title: "stop Android user bubbles with code blocks from overlapping (#5659)",
      },
      {
        kind: "fixed",
        title: "detect PowerShell cmdlet errors in work log rows (#5726)",
      },
      {
        kind: "fixed",
        title: "use import/export-appropriate icons for theme buttons (#5964)",
      },
      {
        kind: "fixed",
        title: "use themed confirmation dialogs (#5624)",
      },
    ],
  },
  {
    version: "0.0.33-nightly.20260810.1055000040",
    date: "2026-08-10",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.33-nightly.20260810.1055000039",
    date: "2026-08-10",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.33-nightly.20260810.1055000038",
    date: "2026-08-10",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.33-nightly.20260810.1055000037",
    date: "2026-08-10",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.33-nightly.20260810.1055000036",
    date: "2026-08-09",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.33-nightly.20260810.1055000035",
    date: "2026-08-09",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.33-nightly.20260810.1055000034",
    date: "2026-08-09",
    items: [
      {
        kind: "new",
        title: "manage agent instruction files from Settings",
      },
    ],
  },
  {
    version: "0.0.33-nightly.20260810.1055000033",
    date: "2026-08-09",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.33-nightly.20260810.1055000032",
    date: "2026-08-09",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.33-nightly.20260810.1055000030",
    date: "2026-08-09",
    items: [
      {
        kind: "fixed",
        title: "replace runner-driven Windows update with an on-box poller",
      },
      {
        kind: "fixed",
        title: "update pills use readable theme foregrounds (#5938)",
      },
      {
        kind: "fixed",
        title: "align project name with headline (#5864)",
      },
      {
        kind: "fixed",
        title: "trait menu closes after you pick a level (#5879)",
      },
      {
        kind: "fixed",
        title: "enable restore defaults after theme mix changes (#5928)",
      },
      {
        kind: "fixed",
        title: "show worktree icon in sidebar v2 (#5909)",
      },
    ],
  },
  {
    version: "0.0.33-nightly.20260810.1054000025",
    date: "2026-08-09",
    items: [
      {
        kind: "improved",
        title: "Under-the-hood stability and maintenance",
      },
    ],
  },
  {
    version: "0.0.33-nightly.20260810.1054000024",
    date: "2026-08-09",
    items: [
      {
        kind: "new",
        title: "update the Windows box natively on each release",
      },
    ],
  },
  {
    version: "0.0.33-nightly.20260810.1054000023",
    date: "2026-08-09",
    items: [
      {
        kind: "fixed",
        title: "strip certificate-type prefix from CSC_NAME",
      },
      {
        kind: "fixed",
        title: "sign from a prepared keychain",
      },
      {
        kind: "fixed",
        title: "allow macOS-only releases",
      },
      {
        kind: "fixed",
        title: "adopt fork bundle id com.sergeserb.t3code",
      },
      {
        kind: "new",
        title: "per-agent sub-thread detail in the Agents panel",
      },
      {
        kind: "fixed",
        title: "explain unborn-HEAD worktree creation failures",
      },
    ],
  },
  {
    version: "0.0.33-nightly.20260809.1043000015",
    date: "2026-08-09",
    items: [
      {
        kind: "fixed",
        title: "make updater tags semver-valid",
      },
      {
        kind: "fixed",
        title: "restore new sessions in fork builds",
      },
      {
        kind: "fixed",
        title: "use dedicated publisher (#14)",
      },
      {
        kind: "fixed",
        title: "queue every main commit (#13)",
      },
      {
        kind: "fixed",
        title: "publish required CI statuses (#12)",
      },
      {
        kind: "fixed",
        title: "grant publisher write access (#10)",
      },
    ],
  },
  {
    version: "0.0.33",
    date: "2026-08-10",
    items: [
      {
        kind: "new",
        title: "Agent instruction files in Settings",
        description:
          "View and edit AGENTS.md and other agent instruction files from Settings → Instructions, without leaving the app.",
      },
    ],
  },
  {
    version: "0.0.32",
    date: "2026-08-07",
    items: [
      {
        kind: "new",
        title: "Configurable fonts and sizes",
        description:
          "Pick interface, prompt, and code fonts — and their sizes — under Settings → Appearance.",
      },
      {
        kind: "new",
        title: "Ghostty-powered terminals",
        description: "Terminal output now renders with libghostty-vt for crisper, faster display.",
      },
      {
        kind: "fixed",
        title: "Steadier chat timeline",
        description: "Messages no longer shift position while a thread streams in.",
      },
    ],
  },
  {
    version: "0.0.31",
    date: "2026-07-29",
    items: [
      {
        kind: "improved",
        title: "Smaller desktop app",
        description: "The installed desktop app is about 300 MB lighter.",
      },
      {
        kind: "improved",
        title: "Less idle CPU and disk churn",
        description: "Native resource diagnostics cut background work while the app sits idle.",
      },
      {
        kind: "fixed",
        title: "Markdown view choice sticks",
        description: "The rendered-markdown toggle is remembered across threads.",
      },
      {
        kind: "fixed",
        title: "Git repositories detected after init",
        description: "Initializing a repository in an open project is picked up right away.",
      },
    ],
  },
];
