/**
 * Built-in catalog of remote MCP servers users can connect as Apps. Every
 * entry was probed live for a Streamable HTTP endpoint (POST initialize →
 * 200, or 401 with an RFC 9728 bearer challenge). Servers that only speak
 * the legacy SSE transport are deliberately absent.
 *
 * Data only — no runtime logic. Clients render it; the server uses `auth`,
 * `scopes`, `authorizeParams`, and `oauthClientFamily` when authorizing.
 *
 * @module appsCatalog
 */
import type { AppAuthKind } from "./apps.ts";

export type AppCategory =
  | "personal"
  | "productivity"
  | "development"
  | "infrastructure"
  | "data"
  | "design"
  | "business"
  | "payments"
  | "knowledge"
  | "automation";

export const APP_CATEGORY_LABELS: Readonly<Record<AppCategory, string>> = {
  personal: "Personal",
  productivity: "Productivity",
  development: "Development",
  infrastructure: "Infrastructure",
  data: "Data",
  design: "Design",
  business: "Business",
  payments: "Payments",
  knowledge: "Docs & knowledge",
  automation: "Automation",
};

export interface AppCatalogEntry {
  /** Stable id; doubles as the default slug. */
  readonly id: string;
  readonly name: string;
  readonly description: string;
  readonly category: AppCategory;
  /** Streamable HTTP MCP endpoint. */
  readonly url: string;
  /** Default auth kind. */
  readonly auth: AppAuthKind;
  /**
   * Set when the authorization server has no dynamic client registration and
   * the user must bring their own OAuth client (see `APP_OAUTH_CLIENT_FAMILIES`).
   */
  readonly oauthClientFamily?: string;
  /** Default OAuth scopes (space-separated); empty = let the server decide. */
  readonly scopes?: string;
  /** Extra authorize-request params (e.g. Google offline access). */
  readonly authorizeParams?: Readonly<Record<string, string>>;
  /** `token` auth is also accepted (PAT / API key) — offered as an alternative. */
  readonly tokenSupported?: boolean;
  /** Header for `token` auth when it isn't `Authorization: Bearer`. */
  readonly tokenHeader?: string;
  /** Where to mint a token / API key. */
  readonly tokenHelpUrl?: string;
  /** Domain whose favicon represents the brand. */
  readonly iconDomain: string;
  /** Monogram background when the favicon can't load. */
  readonly color: string;
}

export interface AppOAuthClientFamily {
  readonly id: string;
  readonly name: string;
  /** Where to create the OAuth client. */
  readonly consoleUrl: string;
  /** Short, ordered setup steps shown next to the Client ID / Secret fields. */
  readonly steps: ReadonlyArray<string>;
}

const GOOGLE_OFFLINE = { access_type: "offline", prompt: "consent" } as const;

export const APP_OAUTH_CLIENT_FAMILIES: ReadonlyArray<AppOAuthClientFamily> = [
  {
    id: "google",
    name: "Google Cloud OAuth client",
    consoleUrl: "https://console.cloud.google.com/apis/credentials",
    steps: [
      "Create (or pick) a Google Cloud project.",
      "Enable the APIs you want: Gmail API, Google Calendar API, Google Drive API, Docs, Sheets, Slides, Chat, People — AND the matching MCP services (gmailmcp.googleapis.com, calendarmcp.googleapis.com, drivemcp.googleapis.com, docsmcp.googleapis.com, sheetsmcp.googleapis.com, slidesmcp.googleapis.com, chatmcp.googleapis.com).",
      "Configure the OAuth consent screen (External, add yourself as a test user while in Testing).",
      "Create an OAuth client ID of type Web application and add the redirect URI shown below.",
      "Paste the Client ID and Client secret here.",
    ],
  },
  {
    id: "github",
    name: "GitHub OAuth App",
    consoleUrl: "https://github.com/settings/developers",
    steps: [
      "OAuth Apps → New OAuth App.",
      "Authorization callback URL = the redirect URI shown below.",
      "Generate a client secret and paste both values here.",
      "Or skip this and connect GitHub with a personal access token instead.",
    ],
  },
  {
    id: "slack",
    name: "Slack app",
    consoleUrl: "https://api.slack.com/apps",
    steps: [
      "Create New App → From scratch.",
      "OAuth & Permissions → add the redirect URI shown below.",
      "Basic Information → copy Client ID and Client Secret here.",
    ],
  },
  {
    id: "hubspot",
    name: "HubSpot app",
    consoleUrl: "https://developers.hubspot.com/",
    steps: [
      "Create a developer account and an app.",
      "Auth → add the redirect URI shown below and copy Client ID / secret here.",
      "Or connect with a private app access token instead.",
    ],
  },
  {
    id: "box",
    name: "Box app",
    consoleUrl: "https://app.box.com/developers/console",
    steps: [
      "Create New App → Custom App → User Authentication (OAuth 2.0).",
      "Configuration → add the redirect URI shown below; copy Client ID / secret here.",
    ],
  },
  {
    id: "render",
    name: "Render OAuth client",
    consoleUrl: "https://dashboard.render.com/settings",
    steps: [
      "Create an OAuth client with the redirect URI shown below, or connect with an API key.",
    ],
  },
  {
    id: "mongodb",
    name: "MongoDB Atlas OAuth client",
    consoleUrl: "https://cloud.mongodb.com/",
    steps: ["Register an OAuth client with the redirect URI shown below."],
  },
  {
    id: "pagerduty",
    name: "PagerDuty OAuth app",
    consoleUrl: "https://app.pagerduty.com/developer/applications",
    steps: [
      "Create an app → OAuth 2.0 → add the redirect URI shown below; copy the client credentials here.",
    ],
  },
];

export const APP_CATALOG: ReadonlyArray<AppCatalogEntry> = [
  // ── Personal / Google Workspace ──────────────────────────────────
  {
    id: "gmail",
    name: "Gmail",
    description: "Search, read, label, draft and send email.",
    category: "personal",
    url: "https://gmailmcp.googleapis.com/mcp/v1",
    auth: "oauth",
    oauthClientFamily: "google",
    scopes: "https://www.googleapis.com/auth/gmail.modify",
    authorizeParams: GOOGLE_OFFLINE,
    iconDomain: "mail.google.com",
    color: "#EA4335",
  },
  {
    id: "google-calendar",
    name: "Google Calendar",
    description: "Read and manage events across your calendars.",
    category: "personal",
    url: "https://calendarmcp.googleapis.com/mcp/v1",
    auth: "oauth",
    oauthClientFamily: "google",
    scopes: "https://www.googleapis.com/auth/calendar",
    authorizeParams: GOOGLE_OFFLINE,
    iconDomain: "calendar.google.com",
    color: "#4285F4",
  },
  {
    id: "google-drive",
    name: "Google Drive",
    description: "Find, read and organize files in Drive.",
    category: "personal",
    url: "https://drivemcp.googleapis.com/mcp/v1",
    auth: "oauth",
    oauthClientFamily: "google",
    scopes: "https://www.googleapis.com/auth/drive",
    authorizeParams: GOOGLE_OFFLINE,
    iconDomain: "drive.google.com",
    color: "#FBBC04",
  },
  {
    id: "google-docs",
    name: "Google Docs",
    description: "Read and edit documents.",
    category: "productivity",
    url: "https://docsmcp.googleapis.com/mcp/v1",
    auth: "oauth",
    oauthClientFamily: "google",
    scopes: "https://www.googleapis.com/auth/documents https://www.googleapis.com/auth/drive",
    authorizeParams: GOOGLE_OFFLINE,
    iconDomain: "docs.google.com",
    color: "#4285F4",
  },
  {
    id: "google-sheets",
    name: "Google Sheets",
    description: "Read and update spreadsheets.",
    category: "productivity",
    url: "https://sheetsmcp.googleapis.com/mcp/v1",
    auth: "oauth",
    oauthClientFamily: "google",
    scopes: "https://www.googleapis.com/auth/spreadsheets https://www.googleapis.com/auth/drive",
    authorizeParams: GOOGLE_OFFLINE,
    iconDomain: "sheets.google.com",
    color: "#34A853",
  },
  {
    id: "google-slides",
    name: "Google Slides",
    description: "Read and edit presentations.",
    category: "productivity",
    url: "https://slidesmcp.googleapis.com/mcp/v1",
    auth: "oauth",
    oauthClientFamily: "google",
    scopes: "https://www.googleapis.com/auth/presentations https://www.googleapis.com/auth/drive",
    authorizeParams: GOOGLE_OFFLINE,
    iconDomain: "slides.google.com",
    color: "#FBBC04",
  },
  {
    id: "google-chat",
    name: "Google Chat",
    description: "Read spaces and post messages.",
    category: "productivity",
    url: "https://chatmcp.googleapis.com/mcp/v1",
    auth: "oauth",
    oauthClientFamily: "google",
    scopes:
      "https://www.googleapis.com/auth/chat.spaces https://www.googleapis.com/auth/chat.messages",
    authorizeParams: GOOGLE_OFFLINE,
    iconDomain: "chat.google.com",
    color: "#34A853",
  },
  {
    id: "google-contacts",
    name: "Google Contacts",
    description: "Look up people and contacts.",
    category: "personal",
    url: "https://people.googleapis.com/mcp/v1",
    auth: "oauth",
    oauthClientFamily: "google",
    scopes: "https://www.googleapis.com/auth/contacts.readonly",
    authorizeParams: GOOGLE_OFFLINE,
    iconDomain: "contacts.google.com",
    color: "#4285F4",
  },
  {
    id: "slack",
    name: "Slack",
    description: "Search messages, read channels and post.",
    category: "productivity",
    url: "https://mcp.slack.com/mcp",
    auth: "oauth",
    oauthClientFamily: "slack",
    scopes:
      "channels:history channels:read chat:write groups:history groups:read im:history im:read im:write mpim:history mpim:read reactions:read reactions:write search:read.public search:read.private users:read users:read.email files:read",
    iconDomain: "slack.com",
    color: "#4A154B",
  },
  {
    id: "notion",
    name: "Notion",
    description: "Search, read and write pages and databases.",
    category: "productivity",
    url: "https://mcp.notion.com/mcp",
    auth: "oauth",
    iconDomain: "notion.so",
    color: "#000000",
  },
  {
    id: "todoist",
    name: "Todoist",
    description: "Manage tasks and projects.",
    category: "personal",
    url: "https://ai.todoist.net/mcp",
    auth: "oauth",
    iconDomain: "todoist.com",
    color: "#E44332",
  },
  {
    id: "dropbox",
    name: "Dropbox",
    description: "Search and read files in Dropbox.",
    category: "personal",
    url: "https://mcp.dropbox.com/mcp",
    auth: "oauth",
    iconDomain: "dropbox.com",
    color: "#0061FF",
  },
  {
    id: "box",
    name: "Box",
    description: "Search, read and manage Box content.",
    category: "productivity",
    url: "https://mcp.box.com/mcp",
    auth: "oauth",
    oauthClientFamily: "box",
    iconDomain: "box.com",
    color: "#0061D5",
  },
  {
    id: "asana",
    name: "Asana",
    description: "Tasks, projects and goals.",
    category: "productivity",
    url: "https://mcp.asana.com/mcp",
    auth: "oauth",
    iconDomain: "asana.com",
    color: "#F06A6A",
  },
  {
    id: "monday",
    name: "monday.com",
    description: "Boards, items and updates.",
    category: "productivity",
    url: "https://mcp.monday.com/mcp",
    auth: "oauth",
    iconDomain: "monday.com",
    color: "#FF3D57",
  },
  {
    id: "clickup",
    name: "ClickUp",
    description: "Tasks, docs and spaces.",
    category: "productivity",
    url: "https://mcp.clickup.com/mcp",
    auth: "oauth",
    iconDomain: "clickup.com",
    color: "#7B68EE",
  },
  {
    id: "airtable",
    name: "Airtable",
    description: "Read and write records across bases.",
    category: "data",
    url: "https://mcp.airtable.com/mcp",
    auth: "oauth",
    iconDomain: "airtable.com",
    color: "#18BFFF",
  },
  {
    id: "fireflies",
    name: "Fireflies",
    description: "Meeting transcripts and summaries.",
    category: "productivity",
    url: "https://api.fireflies.ai/mcp",
    auth: "oauth",
    iconDomain: "fireflies.ai",
    color: "#7B61FF",
  },
  // ── Development ──────────────────────────────────────────────────
  {
    id: "github",
    name: "GitHub",
    description: "Repos, issues, pull requests, actions and code search.",
    category: "development",
    url: "https://api.githubcopilot.com/mcp/",
    auth: "oauth",
    oauthClientFamily: "github",
    scopes: "repo read:org read:user user:email read:project notifications workflow",
    tokenSupported: true,
    tokenHelpUrl: "https://github.com/settings/tokens",
    iconDomain: "github.com",
    color: "#24292F",
  },
  {
    id: "gitlab",
    name: "GitLab",
    description: "Projects, issues, merge requests and pipelines.",
    category: "development",
    url: "https://gitlab.com/api/v4/mcp",
    auth: "oauth",
    iconDomain: "gitlab.com",
    color: "#FC6D26",
  },
  {
    id: "linear",
    name: "Linear",
    description: "Issues, projects, cycles and comments.",
    category: "development",
    url: "https://mcp.linear.app/mcp",
    auth: "oauth",
    iconDomain: "linear.app",
    color: "#5E6AD2",
  },
  {
    id: "atlassian",
    name: "Atlassian (Jira & Confluence)",
    description: "Jira issues and Confluence pages.",
    category: "development",
    url: "https://mcp.atlassian.com/v1/mcp",
    auth: "oauth",
    iconDomain: "atlassian.com",
    color: "#0052CC",
  },
  {
    id: "sentry",
    name: "Sentry",
    description: "Issues, events, traces and Seer analysis.",
    category: "development",
    url: "https://mcp.sentry.dev/mcp",
    auth: "oauth",
    iconDomain: "sentry.io",
    color: "#362D59",
  },
  {
    id: "buildkite",
    name: "Buildkite",
    description: "Pipelines, builds, jobs and logs.",
    category: "development",
    url: "https://mcp.buildkite.com/mcp",
    auth: "oauth",
    iconDomain: "buildkite.com",
    color: "#14CC80",
  },
  {
    id: "jam",
    name: "Jam",
    description: "Bug reports with recordings, logs and network traces.",
    category: "development",
    url: "https://mcp.jam.dev/mcp",
    auth: "oauth",
    iconDomain: "jam.dev",
    color: "#7A5AF8",
  },
  {
    id: "semgrep",
    name: "Semgrep",
    description: "Static analysis findings and rules.",
    category: "development",
    url: "https://mcp.semgrep.ai/mcp",
    auth: "oauth",
    iconDomain: "semgrep.dev",
    color: "#00A67D",
  },
  {
    id: "expo",
    name: "Expo",
    description: "EAS builds, updates and projects.",
    category: "development",
    url: "https://mcp.expo.dev/mcp",
    auth: "oauth",
    iconDomain: "expo.dev",
    color: "#000020",
  },
  {
    id: "globalping",
    name: "Globalping",
    description: "Ping, traceroute, DNS and HTTP checks from anywhere.",
    category: "development",
    url: "https://mcp.globalping.dev/mcp",
    auth: "oauth",
    iconDomain: "globalping.io",
    color: "#17D4A7",
  },
  // ── Infrastructure ───────────────────────────────────────────────
  {
    id: "vercel",
    name: "Vercel",
    description: "Projects, deployments and logs.",
    category: "infrastructure",
    url: "https://mcp.vercel.com/",
    auth: "oauth",
    iconDomain: "vercel.com",
    color: "#000000",
  },
  {
    id: "netlify",
    name: "Netlify",
    description: "Sites, deploys and env vars.",
    category: "infrastructure",
    url: "https://netlify-mcp.netlify.app/mcp",
    auth: "oauth",
    iconDomain: "netlify.com",
    color: "#00C7B7",
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    description: "Workers, KV, R2, D1 and account resources.",
    category: "infrastructure",
    url: "https://bindings.mcp.cloudflare.com/mcp",
    auth: "oauth",
    iconDomain: "cloudflare.com",
    color: "#F38020",
  },
  {
    id: "cloudflare-observability",
    name: "Cloudflare Observability",
    description: "Workers logs and analytics.",
    category: "infrastructure",
    url: "https://observability.mcp.cloudflare.com/mcp",
    auth: "oauth",
    iconDomain: "cloudflare.com",
    color: "#F38020",
  },
  {
    id: "render",
    name: "Render",
    description: "Services, deploys, logs and Postgres.",
    category: "infrastructure",
    url: "https://mcp.render.com/mcp",
    auth: "token",
    oauthClientFamily: "render",
    tokenSupported: true,
    tokenHelpUrl: "https://dashboard.render.com/settings#api-keys",
    iconDomain: "render.com",
    color: "#46E3B7",
  },
  {
    id: "supabase",
    name: "Supabase",
    description: "Projects, database, SQL and edge functions.",
    category: "infrastructure",
    url: "https://mcp.supabase.com/mcp",
    auth: "oauth",
    iconDomain: "supabase.com",
    color: "#3ECF8E",
  },
  {
    id: "neon",
    name: "Neon",
    description: "Serverless Postgres projects and branches.",
    category: "infrastructure",
    url: "https://mcp.neon.tech/mcp",
    auth: "oauth",
    iconDomain: "neon.tech",
    color: "#00E599",
  },
  {
    id: "prisma-postgres",
    name: "Prisma Postgres",
    description: "Manage Prisma Postgres databases.",
    category: "infrastructure",
    url: "https://mcp.prisma.io/mcp",
    auth: "oauth",
    iconDomain: "prisma.io",
    color: "#2D3748",
  },
  {
    id: "mongodb",
    name: "MongoDB Atlas",
    description: "Clusters, databases and queries.",
    category: "infrastructure",
    url: "https://mcp.mongodb.com/mcp",
    auth: "oauth",
    oauthClientFamily: "mongodb",
    iconDomain: "mongodb.com",
    color: "#00ED64",
  },
  {
    id: "instant",
    name: "InstantDB",
    description: "Apps, schema and permissions.",
    category: "infrastructure",
    url: "https://mcp.instantdb.com/mcp",
    auth: "oauth",
    iconDomain: "instantdb.com",
    color: "#111111",
  },
  {
    id: "grafana",
    name: "Grafana",
    description: "Dashboards, datasources and alerts.",
    category: "infrastructure",
    url: "https://mcp.grafana.com/mcp",
    auth: "oauth",
    iconDomain: "grafana.com",
    color: "#F46800",
  },
  {
    id: "posthog",
    name: "PostHog",
    description: "Insights, feature flags, errors and experiments.",
    category: "data",
    url: "https://mcp.posthog.com/mcp",
    auth: "oauth",
    iconDomain: "posthog.com",
    color: "#F54E00",
  },
  {
    id: "honeycomb",
    name: "Honeycomb",
    description: "Query traces and events.",
    category: "infrastructure",
    url: "https://mcp.honeycomb.io/mcp",
    auth: "oauth",
    iconDomain: "honeycomb.io",
    color: "#FFB000",
  },
  {
    id: "pagerduty",
    name: "PagerDuty",
    description: "Incidents, on-call and services.",
    category: "infrastructure",
    url: "https://mcp.pagerduty.com/mcp",
    auth: "oauth",
    oauthClientFamily: "pagerduty",
    iconDomain: "pagerduty.com",
    color: "#06AC38",
  },
  {
    id: "workos",
    name: "WorkOS",
    description: "Organizations, users and SSO connections.",
    category: "infrastructure",
    url: "https://mcp.workos.com/mcp",
    auth: "oauth",
    iconDomain: "workos.com",
    color: "#6363F1",
  },
  {
    id: "resend",
    name: "Resend",
    description: "Send email and inspect deliveries.",
    category: "infrastructure",
    url: "https://mcp.resend.com/mcp",
    auth: "oauth",
    iconDomain: "resend.com",
    color: "#000000",
  },
  {
    id: "cloudinary",
    name: "Cloudinary",
    description: "Search and manage media assets.",
    category: "infrastructure",
    url: "https://asset-management.mcp.cloudinary.com/mcp",
    auth: "oauth",
    iconDomain: "cloudinary.com",
    color: "#3448C5",
  },
  // ── Design ───────────────────────────────────────────────────────
  {
    id: "figma",
    name: "Figma",
    description: "Read designs, components and variables.",
    category: "design",
    url: "https://mcp.figma.com/mcp",
    auth: "oauth",
    iconDomain: "figma.com",
    color: "#F24E1E",
  },
  {
    id: "canva",
    name: "Canva",
    description: "Designs, folders and exports.",
    category: "design",
    url: "https://mcp.canva.com/mcp",
    auth: "oauth",
    iconDomain: "canva.com",
    color: "#00C4CC",
  },
  {
    id: "miro",
    name: "Miro",
    description: "Boards, sticky notes and diagrams.",
    category: "design",
    url: "https://mcp.miro.com/",
    auth: "oauth",
    iconDomain: "miro.com",
    color: "#FFD02F",
  },
  {
    id: "webflow",
    name: "Webflow",
    description: "Sites, CMS collections and pages.",
    category: "design",
    url: "https://mcp.webflow.com/mcp",
    auth: "oauth",
    iconDomain: "webflow.com",
    color: "#146EF5",
  },
  {
    id: "wix",
    name: "Wix",
    description: "Sites, content and business data.",
    category: "design",
    url: "https://mcp.wix.com/mcp",
    auth: "oauth",
    iconDomain: "wix.com",
    color: "#0C6EFC",
  },
  // ── Business ─────────────────────────────────────────────────────
  {
    id: "hubspot",
    name: "HubSpot",
    description: "Contacts, companies, deals and tickets.",
    category: "business",
    url: "https://mcp.hubspot.com/",
    auth: "oauth",
    oauthClientFamily: "hubspot",
    tokenSupported: true,
    tokenHelpUrl: "https://developers.hubspot.com/docs/api/private-apps",
    iconDomain: "hubspot.com",
    color: "#FF7A59",
  },
  {
    id: "intercom",
    name: "Intercom",
    description: "Conversations, contacts and articles.",
    category: "business",
    url: "https://mcp.intercom.com/mcp",
    auth: "oauth",
    iconDomain: "intercom.com",
    color: "#286EFA",
  },
  {
    id: "attio",
    name: "Attio",
    description: "CRM records, lists and notes.",
    category: "business",
    url: "https://mcp.attio.com/mcp",
    auth: "oauth",
    iconDomain: "attio.com",
    color: "#111111",
  },
  {
    id: "close",
    name: "Close",
    description: "Leads, contacts, opportunities and activities.",
    category: "business",
    url: "https://mcp.close.com/mcp",
    auth: "oauth",
    iconDomain: "close.com",
    color: "#1463FF",
  },
  {
    id: "apollo",
    name: "Apollo.io",
    description: "People and company enrichment and search.",
    category: "business",
    url: "https://mcp.apollo.io/mcp",
    auth: "oauth",
    iconDomain: "apollo.io",
    color: "#FDC300",
  },
  {
    id: "egnyte",
    name: "Egnyte",
    description: "Files, folders and permissions.",
    category: "business",
    url: "https://mcp-server.egnyte.com/mcp",
    auth: "oauth",
    iconDomain: "egnyte.com",
    color: "#00A651",
  },
  // ── Payments ─────────────────────────────────────────────────────
  {
    id: "stripe",
    name: "Stripe",
    description: "Customers, payments, subscriptions and invoices.",
    category: "payments",
    url: "https://mcp.stripe.com/",
    auth: "oauth",
    tokenSupported: true,
    tokenHelpUrl: "https://dashboard.stripe.com/apikeys",
    iconDomain: "stripe.com",
    color: "#635BFF",
  },
  {
    id: "paypal",
    name: "PayPal",
    description: "Orders, invoices, subscriptions and disputes.",
    category: "payments",
    url: "https://mcp.paypal.com/mcp",
    auth: "oauth",
    iconDomain: "paypal.com",
    color: "#003087",
  },
  {
    id: "square",
    name: "Square",
    description: "Payments, catalog, customers and orders.",
    category: "payments",
    url: "https://mcp.squareup.com/mcp",
    auth: "oauth",
    iconDomain: "squareup.com",
    color: "#000000",
  },
  {
    id: "ramp",
    name: "Ramp",
    description: "Cards, transactions, bills and reimbursements.",
    category: "payments",
    url: "https://ramp-mcp-remote.ramp.com/mcp",
    auth: "oauth",
    iconDomain: "ramp.com",
    color: "#E4F222",
  },
  // ── Automation ───────────────────────────────────────────────────
  {
    id: "zapier",
    name: "Zapier",
    description: "Thousands of apps through your Zapier MCP actions.",
    category: "automation",
    url: "https://mcp.zapier.com/api/mcp/mcp",
    auth: "token",
    tokenHelpUrl: "https://mcp.zapier.com/",
    iconDomain: "zapier.com",
    color: "#FF4F00",
  },
  // ── Docs & knowledge (no auth) ───────────────────────────────────
  {
    id: "context7",
    name: "Context7",
    description: "Up-to-date docs and code examples for any library.",
    category: "knowledge",
    url: "https://mcp.context7.com/mcp",
    auth: "none",
    iconDomain: "context7.com",
    color: "#111111",
  },
  {
    id: "deepwiki",
    name: "DeepWiki",
    description: "Ask questions about any public GitHub repo.",
    category: "knowledge",
    url: "https://mcp.deepwiki.com/mcp",
    auth: "none",
    iconDomain: "deepwiki.com",
    color: "#111111",
  },
  {
    id: "hugging-face",
    name: "Hugging Face",
    description: "Models, datasets, Spaces and papers.",
    category: "knowledge",
    url: "https://huggingface.co/mcp",
    auth: "none",
    iconDomain: "huggingface.co",
    color: "#FFD21E",
  },
  {
    id: "microsoft-learn",
    name: "Microsoft Learn",
    description: "Official Microsoft and Azure documentation.",
    category: "knowledge",
    url: "https://learn.microsoft.com/api/mcp",
    auth: "none",
    iconDomain: "learn.microsoft.com",
    color: "#0078D4",
  },
  {
    id: "cloudflare-docs",
    name: "Cloudflare Docs",
    description: "Search Cloudflare developer docs.",
    category: "knowledge",
    url: "https://docs.mcp.cloudflare.com/mcp",
    auth: "none",
    iconDomain: "developers.cloudflare.com",
    color: "#F38020",
  },
  {
    id: "aws-knowledge",
    name: "AWS Knowledge",
    description: "AWS docs, API references and best practices.",
    category: "knowledge",
    url: "https://knowledge-mcp.global.api.aws",
    auth: "none",
    iconDomain: "aws.amazon.com",
    color: "#FF9900",
  },
  {
    id: "convex-docs",
    name: "Convex Docs",
    description: "Convex backend documentation.",
    category: "knowledge",
    url: "https://mcp.convex.dev/mcp",
    auth: "none",
    iconDomain: "convex.dev",
    color: "#EE342F",
  },
  {
    id: "clerk-docs",
    name: "Clerk Docs",
    description: "Clerk authentication documentation.",
    category: "knowledge",
    url: "https://mcp.clerk.com/mcp",
    auth: "none",
    iconDomain: "clerk.com",
    color: "#6C47FF",
  },
  {
    id: "exa",
    name: "Exa Search",
    description: "Neural web search and page contents.",
    category: "knowledge",
    url: "https://mcp.exa.ai/mcp",
    auth: "none",
    iconDomain: "exa.ai",
    color: "#1F40ED",
  },
  {
    id: "tavily",
    name: "Tavily",
    description: "Web search, extract and crawl for agents.",
    category: "knowledge",
    url: "https://mcp.tavily.com/mcp",
    auth: "oauth",
    iconDomain: "tavily.com",
    color: "#468BFF",
  },
];

const catalogById = new Map(APP_CATALOG.map((entry) => [entry.id, entry] as const));
const familyById = new Map(APP_OAUTH_CLIENT_FAMILIES.map((family) => [family.id, family] as const));

export function findAppCatalogEntry(id: string | null | undefined): AppCatalogEntry | undefined {
  return id ? catalogById.get(id) : undefined;
}

export function findAppOAuthClientFamily(id: string | undefined): AppOAuthClientFamily | undefined {
  return id ? familyById.get(id) : undefined;
}
